/**
 * Tupaia
 * Copyright (c) 2017 - 2020 Beyond Essential Systems Pty Ltd
 */

const COUNT_PER_ORG_GROUP = 'COUNT_PER_ORG_GROUP';
const COUNT_PER_PERIOD_PER_ORG_GROUP = 'COUNT_PER_PERIOD_PER_ORG_GROUP';
const FINAL_EACH_DAY_FILL_EMPTY_DAYS = 'FINAL_EACH_DAY_FILL_EMPTY_DAYS';
const FINAL_EACH_DAY = 'FINAL_EACH_DAY';
const FINAL_EACH_MONTH_FILL_EMPTY_MONTHS = 'FINAL_EACH_MONTH_FILL_EMPTY_MONTHS';
const FINAL_EACH_MONTH_PREFER_DAILY_PERIOD = 'FINAL_EACH_MONTH_PREFER_DAILY_PERIOD'; // I.e. use 20180214 over 201802
const FINAL_EACH_MONTH = 'FINAL_EACH_MONTH';
const FINAL_EACH_QUARTER_FILL_EMPTY_QUARTERS = 'FINAL_EACH_QUARTER_FILL_EMPTY_QUARTERS';
const FINAL_EACH_QUARTER = 'FINAL_EACH_QUARTER';
const FINAL_EACH_WEEK_FILL_EMPTY_WEEKS = 'FINAL_EACH_WEEK_FILL_EMPTY_WEEKS';
const FINAL_EACH_WEEK = 'FINAL_EACH_WEEK';
const FINAL_EACH_YEAR_FILL_EMPTY_YEARS = 'FINAL_EACH_YEAR_FILL_EMPTY_YEARS';
const FINAL_EACH_YEAR = 'FINAL_EACH_YEAR';
const MOST_RECENT_PER_ORG_GROUP = 'MOST_RECENT_PER_ORG_GROUP';
const MOST_RECENT = 'MOST_RECENT';
const OFFSET_PERIOD = 'OFFSET_PERIOD';
const RAW = 'RAW';
const REPLACE_ORG_UNIT_WITH_ORG_GROUP = 'REPLACE_ORG_UNIT_WITH_ORG_GROUP';
const SUM_EACH_QUARTER = 'SUM_EACH_QUARTER';
const SUM_EACH_YEAR = 'SUM_EACH_YEAR';
const SUM_EACH_MONTH = 'SUM_EACH_MONTH';
const SUM_EACH_WEEK = 'SUM_EACH_WEEK';
const SUM_MOST_RECENT_PER_FACILITY = 'SUM_MOST_RECENT_PER_FACILITY';
const SUM_PER_ORG_GROUP = 'SUM_PER_ORG_GROUP';
const SUM_PER_PERIOD_PER_ORG_GROUP = 'SUM_PER_PERIOD_PER_ORG_GROUP';
const SUM_PREVIOUS_EACH_DAY = 'SUM_PREVIOUS_EACH_DAY';
const SUM_UNTIL_CURRENT_DAY = 'SUM_UNTIL_CURRENT_DAY';
const SUM = 'SUM';

export const AGGREGATION_TYPES_META_DATA = [
  { code: COUNT_PER_ORG_GROUP, description: 'COUNT_PER_ORG_GROUP' },
  { code: COUNT_PER_PERIOD_PER_ORG_GROUP, description: 'COUNT_PER_PERIOD_PER_ORG_GROUP' },
  { code: FINAL_EACH_DAY_FILL_EMPTY_DAYS, description: 'FINAL_EACH_DAY_FILL_EMPTY_DAYS' },
  { code: FINAL_EACH_DAY, description: 'FINAL_EACH_DAY' },
  { code: FINAL_EACH_MONTH_FILL_EMPTY_MONTHS, description: 'FINAL_EACH_MONTH_FILL_EMPTY_MONTHS' },
  {
    code: FINAL_EACH_MONTH_PREFER_DAILY_PERIOD,
    description: 'FINAL_EACH_MONTH_PREFER_DAILY_PERIOD',
  },
  { code: FINAL_EACH_MONTH, description: 'FINAL_EACH_MONTH' },
  {
    code: FINAL_EACH_QUARTER_FILL_EMPTY_QUARTERS,
    description: 'FINAL_EACH_QUARTER_FILL_EMPTY_QUARTERS',
  },
  { code: FINAL_EACH_QUARTER, description: 'FINAL_EACH_QUARTER' },
  { code: FINAL_EACH_WEEK_FILL_EMPTY_WEEKS, description: 'FINAL_EACH_WEEK_FILL_EMPTY_WEEKS' },
  { code: FINAL_EACH_WEEK, description: 'FINAL_EACH_WEEK' },
  { code: FINAL_EACH_YEAR_FILL_EMPTY_YEARS, description: 'FINAL_EACH_YEAR_FILL_EMPTY_YEARS' },
  { code: FINAL_EACH_YEAR, description: 'FINAL_EACH_YEAR' },
  { code: MOST_RECENT_PER_ORG_GROUP, description: 'MOST_RECENT_PER_ORG_GROUP' },
  { code: MOST_RECENT, description: 'MOST_RECENT' },
  { code: OFFSET_PERIOD, description: 'OFFSET_PERIOD' },
  { code: RAW, description: 'RAW' },
  { code: REPLACE_ORG_UNIT_WITH_ORG_GROUP, description: 'REPLACE_ORG_UNIT_WITH_ORG_GROUP' },
  { code: SUM_EACH_QUARTER, description: 'SUM_EACH_QUARTER' },
  { code: SUM_EACH_YEAR, description: 'SUM_EACH_YEAR' },
  { code: SUM_EACH_MONTH, description: 'SUM_EACH_MONTH' },
  { code: SUM_EACH_WEEK, description: 'SUM_EACH_WEEK' },
  { code: SUM_MOST_RECENT_PER_FACILITY, description: 'SUM_MOST_RECENT_PER_FACILITY' },
  { code: SUM_PER_ORG_GROUP, description: 'SUM_PER_ORG_GROUP' },
  { code: SUM_PER_PERIOD_PER_ORG_GROUP, description: 'SUM_PER_PERIOD_PER_ORG_GROUP' },
  { code: SUM_PREVIOUS_EACH_DAY, description: 'SUM_PREVIOUS_EACH_DAY' },
  { code: SUM_UNTIL_CURRENT_DAY, description: 'SUM_UNTIL_CURRENT_DAY' },
  { code: SUM, description: 'SUM' },
];

export const AGGREGATION_TYPES = Object.fromEntries(
  AGGREGATION_TYPES_META_DATA.map(({ code }) => [code, code]),
);
