/**
 * Tupaia MediTrak
 * Copyright (c) 2018 Beyond Essential Systems Pty Ltd
 */

export const IMPORT_EXPORT_START = 'IMPORT_EXPORT_START';
export const IMPORT_EXPORT_ERROR = 'IMPORT_EXPORT_ERROR';
export const IMPORT_EXPORT_SUCCESS = 'IMPORT_EXPORT_SUCCESS';
export const IMPORT_DIALOG_OPEN = 'IMPORT_DIALOG_OPEN';
export const IMPORT_EXPORT_DISMISS = 'IMPORT_EXPORT_DISMISS';
export const FILTERED_EXPORT_FETCH_BEGIN = 'FILTERED_EXPORT_FETCH_BEGIN';
export const FILTERED_EXPORT_FETCH_SUCCESS = 'FILTERED_EXPORT_FETCH_SUCCESS';
export const FILTERED_EXPORT_TOGGLE = 'FILTERED_EXPORT_TOGGLE';
export const FILTERED_EXPORT_ERROR = 'FILTERED_EXPORT_ERROR';

export const DATA_CHANGE_ACTIONS = {
  start: IMPORT_EXPORT_START,
  finish: IMPORT_EXPORT_SUCCESS,
  error: IMPORT_EXPORT_ERROR,
};
