/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const AccessRequestUpdateSchema = {
	"type": "object",
	"properties": {
		"approved": {
			"type": "boolean"
		},
		"created_time": {
			"type": "string",
			"format": "date-time"
		},
		"entity_id": {
			"type": "string"
		},
		"id": {
			"type": "string"
		},
		"message": {
			"type": "string"
		},
		"note": {
			"type": "string"
		},
		"permission_group_id": {
			"type": "string"
		},
		"processed_by": {
			"type": "string"
		},
		"processed_date": {
			"type": "string",
			"format": "date-time"
		},
		"project_id": {
			"type": "string"
		},
		"user_id": {
			"type": "string"
		}
	},
	"additionalProperties": false
}
