/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const AncestorDescendantRelationSchema = {
	"type": "object",
	"properties": {
		"ancestor_id": {
			"type": "string"
		},
		"descendant_id": {
			"type": "string"
		},
		"entity_hierarchy_id": {
			"type": "string"
		},
		"generational_distance": {
			"type": "number"
		},
		"id": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"ancestor_id",
		"descendant_id",
		"entity_hierarchy_id",
		"generational_distance",
		"id"
	]
}
