/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const AnswerSchema = {
	"type": "object",
	"properties": {
		"id": {
			"type": "string"
		},
		"question_id": {
			"type": "string"
		},
		"survey_response_id": {
			"type": "string"
		},
		"text": {
			"type": "string"
		},
		"type": {
			"type": "string"
		},
		"updated_at_sync_tick": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"id",
		"question_id",
		"survey_response_id",
		"type",
		"updated_at_sync_tick"
	]
}
