/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const AnswerCreateSchema = {
	"type": "object",
	"properties": {
		"question_id": {
			"type": "string"
		},
		"survey_response_id": {
			"type": "string"
		},
		"text": {
			"type": "string"
		},
		"type": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"question_id",
		"survey_response_id",
		"type"
	]
}
