/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const ApiClientCreateSchema = {
	"type": "object",
	"properties": {
		"secret_key_hash": {
			"type": "string"
		},
		"user_account_id": {
			"type": "string"
		},
		"username": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"secret_key_hash",
		"username"
	]
}
