/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const ArithmeticQuestionConfigSchema = {
	"type": "object",
	"properties": {
		"formula": {
			"type": "string"
		},
		"defaultValues": {
			"type": "object",
			"additionalProperties": false
		},
		"answerDisplayText": {
			"type": "string"
		},
		"valueTranslation": {
			"type": "object",
			"additionalProperties": false
		}
	},
	"additionalProperties": false,
	"required": [
		"formula"
	]
}
