/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const AutocompleteQuestionConfigSchema = {
	"type": "object",
	"properties": {
		"createNew": {
			"type": "boolean"
		},
		"attributes": {
			"type": "object",
			"additionalProperties": {
				"type": "object",
				"properties": {
					"questionId": {
						"type": "string"
					}
				},
				"additionalProperties": false,
				"required": [
					"questionId"
				]
			}
		}
	},
	"additionalProperties": false
}
