/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const BaseReportSchema = {
	"type": "object",
	"properties": {
		"type": {
			"type": "string"
		},
		"data": {
			"type": "array",
			"items": {
				"type": "object",
				"additionalProperties": false
			}
		},
		"startDate": {
			"type": "string"
		},
		"endDate": {
			"type": "string"
		},
		"period": {
			"type": "object",
			"properties": {
				"earliestAvailable": {
					"type": "string"
				},
				"latestAvailable": {
					"type": "string"
				},
				"requested": {
					"type": "string"
				}
			},
			"additionalProperties": false
		}
	},
	"additionalProperties": false,
	"required": [
		"endDate",
		"startDate"
	]
}
