/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const BaseMapOverlayConfigSchema = {
	"type": "object",
	"properties": {
		"customLabel": {
			"description": "Override the map overlay name",
			"type": "string"
		},
		"datePickerLimits": {
			"description": "Maximum date ranges that the date picker can be used to choose from",
			"type": "object",
			"properties": {
				"start": {
					"type": "object",
					"properties": {
						"unit": {
							"description": "Time unit to offset by",
							"enum": [
								"day",
								"month",
								"quarter",
								"week",
								"year"
							],
							"type": "string"
						},
						"offset": {
							"description": "Offset distance (can be negative to offset to an earlier date)",
							"type": "number"
						},
						"modifier": {
							"description": "Used to modify the offset by either moving the date to the start/end of the modifier unit",
							"enum": [
								"end_of",
								"start_of"
							],
							"type": "string"
						},
						"modifierUnit": {
							"description": "Time unit to modify the offset by",
							"enum": [
								"day",
								"month",
								"quarter",
								"week",
								"year"
							],
							"type": "string"
						}
					},
					"additionalProperties": false,
					"required": [
						"unit"
					]
				},
				"end": {
					"type": "object",
					"properties": {
						"unit": {
							"description": "Time unit to offset by",
							"enum": [
								"day",
								"month",
								"quarter",
								"week",
								"year"
							],
							"type": "string"
						},
						"offset": {
							"description": "Offset distance (can be negative to offset to an earlier date)",
							"type": "number"
						},
						"modifier": {
							"description": "Used to modify the offset by either moving the date to the start/end of the modifier unit",
							"enum": [
								"end_of",
								"start_of"
							],
							"type": "string"
						},
						"modifierUnit": {
							"description": "Time unit to modify the offset by",
							"enum": [
								"day",
								"month",
								"quarter",
								"week",
								"year"
							],
							"type": "string"
						}
					},
					"additionalProperties": false,
					"required": [
						"unit"
					]
				}
			},
			"additionalProperties": false
		},
		"defaultTimePeriod": {
			"description": "Initial date range for this viz.\nEither a single offset, or an ISO string / offset for start/end date\neg.\n// Single offset\n\"defaultTimePeriod\": {\n  \"unit\": \"week\",\n  \"offset\": 7\n}\n\n// Explicit start/end dates\n\"defaultTimePeriod\": {\n  \"start\": \"2022-10-01\",\n  \"end\": \"2023-06-30\"\n}\n\n// Start/end date offsets\n\"defaultTimePeriod\": {\n  \"start\": {\n    \"unit\": \"week\",\n    \"offset\": -52\n  },\n  \"end\": {\n    \"unit\": \"week\",\n    \"offset\": 3\n  }\n}",
			"anyOf": [
				{
					"type": "object",
					"properties": {
						"unit": {
							"description": "Time unit to offset by",
							"enum": [
								"day",
								"month",
								"quarter",
								"week",
								"year"
							],
							"type": "string"
						},
						"offset": {
							"description": "Offset distance (can be negative to offset to an earlier date)",
							"type": "number"
						},
						"modifier": {
							"description": "Used to modify the offset by either moving the date to the start/end of the modifier unit",
							"enum": [
								"end_of",
								"start_of"
							],
							"type": "string"
						},
						"modifierUnit": {
							"description": "Time unit to modify the offset by",
							"enum": [
								"day",
								"month",
								"quarter",
								"week",
								"year"
							],
							"type": "string"
						}
					},
					"additionalProperties": false,
					"required": [
						"unit"
					]
				},
				{
					"type": "object",
					"properties": {
						"start": {
							"description": "Either an ISO Date string, or an offset object",
							"anyOf": [
								{
									"type": "object",
									"properties": {
										"unit": {
											"description": "Time unit to offset by",
											"enum": [
												"day",
												"month",
												"quarter",
												"week",
												"year"
											],
											"type": "string"
										},
										"offset": {
											"description": "Offset distance (can be negative to offset to an earlier date)",
											"type": "number"
										},
										"modifier": {
											"description": "Used to modify the offset by either moving the date to the start/end of the modifier unit",
											"enum": [
												"end_of",
												"start_of"
											],
											"type": "string"
										},
										"modifierUnit": {
											"description": "Time unit to modify the offset by",
											"enum": [
												"day",
												"month",
												"quarter",
												"week",
												"year"
											],
											"type": "string"
										}
									},
									"additionalProperties": false,
									"required": [
										"unit"
									]
								},
								{
									"type": "string"
								}
							]
						},
						"end": {
							"description": "Either an ISO Date string, or an offset object",
							"anyOf": [
								{
									"type": "object",
									"properties": {
										"unit": {
											"description": "Time unit to offset by",
											"enum": [
												"day",
												"month",
												"quarter",
												"week",
												"year"
											],
											"type": "string"
										},
										"offset": {
											"description": "Offset distance (can be negative to offset to an earlier date)",
											"type": "number"
										},
										"modifier": {
											"description": "Used to modify the offset by either moving the date to the start/end of the modifier unit",
											"enum": [
												"end_of",
												"start_of"
											],
											"type": "string"
										},
										"modifierUnit": {
											"description": "Time unit to modify the offset by",
											"enum": [
												"day",
												"month",
												"quarter",
												"week",
												"year"
											],
											"type": "string"
										}
									},
									"additionalProperties": false,
									"required": [
										"unit"
									]
								},
								{
									"type": "string"
								}
							]
						}
					},
					"additionalProperties": false
				}
			]
		},
		"disableRenameLegend": {
			"description": "Values in the legend will be renamed if the majority of values have different 'displayValueKey'.\nThis setting disabled that behaviour.",
			"type": "boolean"
		},
		"displayOnLevel": {
			"description": "This setting defines the level of the entity hierarchy from where we start rendering the map overlay.\nUse this if we want to only render the map overlay below a certain level.\neg. If rendering the map overlay at the country level causes performance issues, set displayOnLevel: SubDistrict to only start rendering at Sub District",
			"enum": [
				"Asset",
				"BesAsset",
				"BesOffice",
				"Business",
				"Case",
				"CaseContact",
				"Catchment",
				"City",
				"Commune",
				"Complaint",
				"Consumable",
				"Country",
				"Disaster",
				"District",
				"DistrictOperational",
				"Document",
				"DocumentGroup",
				"EnumerationArea",
				"Facility",
				"FacilityBuilding",
				"FacilityDivision",
				"FacilitySection",
				"Farm",
				"FetpGraduate",
				"FieldStation",
				"FijiAspenFacility",
				"HealthClinicBoundary",
				"HospitalArea",
				"HospitalWard",
				"Household",
				"Incident",
				"IncidentReported",
				"Individual",
				"Institute",
				"IrdDistrict",
				"IrdProvince",
				"IrdTehsil",
				"IrdVillage",
				"KiuarArea",
				"KiuarFacility",
				"LarvalHabitat",
				"LarvalSample",
				"LocalGovernment",
				"Maintenance",
				"MedicalArea",
				"MsupplyStore",
				"NursingZone",
				"PacmossiAsset",
				"PacmossiAssetFacility",
				"PacmossiAssetSubFacility",
				"PacmossiConsumable",
				"PacmossiConsumableBatch",
				"PacmossiDistrict",
				"PacmossiInsecticideTest",
				"PacmossiSprayingSite",
				"PacmossiVillage",
				"Pharmacy",
				"Policy",
				"Postcode",
				"Project",
				"RehabFacilityModel",
				"RepairRequest",
				"School",
				"SparePart",
				"SrhDistrict",
				"SrhSubDistrict",
				"SubCatchment",
				"SubDistrict",
				"SubFacility",
				"Supermarket",
				"TamanuCountry",
				"TmfDistrict",
				"TmfFacility",
				"TmfProject",
				"TmfSubDistrict",
				"Transfer",
				"Trap",
				"Vehicle",
				"Village",
				"VisitingSpecialist",
				"WaterSample",
				"Wholesaler",
				"WishSubDistrict",
				"World",
				"asset",
				"bes_asset",
				"bes_office",
				"business",
				"case",
				"case_contact",
				"catchment",
				"city",
				"commune",
				"complaint",
				"consumable",
				"country",
				"disaster",
				"district",
				"district_operational",
				"document",
				"document_group",
				"enumeration_area",
				"facility",
				"facility_building",
				"facility_division",
				"facility_section",
				"farm",
				"fetp_graduate",
				"field_station",
				"fiji_aspen_facility",
				"health_clinic_boundary",
				"hospital_area",
				"hospital_ward",
				"household",
				"incident",
				"incident_reported",
				"individual",
				"institute",
				"ird_district",
				"ird_province",
				"ird_tehsil",
				"ird_village",
				"kiuar_area",
				"kiuar_facility",
				"larval_habitat",
				"larval_sample",
				"local_government",
				"maintenance",
				"medical_area",
				"msupply_store",
				"nursing_zone",
				"pacmossi_asset",
				"pacmossi_asset_facility",
				"pacmossi_asset_sub_facility",
				"pacmossi_consumable",
				"pacmossi_consumable_batch",
				"pacmossi_district",
				"pacmossi_insecticide_test",
				"pacmossi_spraying_site",
				"pacmossi_village",
				"pharmacy",
				"policy",
				"postcode",
				"project",
				"rehab_facility_model",
				"repair_request",
				"school",
				"spare_part",
				"srh_district",
				"srh_sub_district",
				"sub_catchment",
				"sub_district",
				"sub_facility",
				"supermarket",
				"tamanu_country",
				"tmf_district",
				"tmf_facility",
				"tmf_project",
				"tmf_sub_district",
				"transfer",
				"trap",
				"vehicle",
				"village",
				"visiting_specialist",
				"water_sample",
				"wholesaler",
				"wish_sub_district",
				"world"
			],
			"type": "string"
		},
		"displayedValueKey": {
			"description": "Use to override the default column of data that we display",
			"enum": [
				"facilityTypeName",
				"name",
				"originalValue",
				"schoolTypeName"
			],
			"type": "string"
		},
		"hideByDefault": {
			"description": "This is keyed by the value, e.g. 'null': true, and determines whether the specific value should be hidden by default",
			"type": "object",
			"additionalProperties": {
				"type": "boolean"
			}
		},
		"hideFromLegend": {
			"description": "Whether to include this map overlay in the legend",
			"type": "boolean"
		},
		"hideFromMenu": {
			"description": "Whether to include this map overlay in the map overlay selector menu",
			"type": "boolean"
		},
		"hideFromPopup": {
			"description": "Whether to map overlay in the popup/tooltip",
			"type": "boolean"
		},
		"info": {
			"description": "Configure the 'i' icon information in the map overlay menu",
			"type": "object",
			"properties": {
				"reference": {
					"description": "Props for the reference prop of the `ReferenceTooltip` ui-component. It can have either a piece\nof plaintext to display in the tooltip, or a named link; but not both.",
					"anyOf": [
						{
							"description": "One of the two shapes which {@link ReferenceProps} can take.",
							"type": "object",
							"properties": {
								"text": {
									"type": "string"
								}
							},
							"additionalProperties": false,
							"required": [
								"text"
							]
						},
						{
							"description": "One of the two shapes which {@link ReferenceProps} can take.",
							"type": "object",
							"properties": {
								"name": {
									"type": "string"
								},
								"link": {
									"type": "string"
								}
							},
							"additionalProperties": false,
							"required": [
								"link",
								"name"
							]
						}
					]
				}
			},
			"additionalProperties": false
		},
		"isTimePeriodEditable": {
			"description": "Whether this map overlay supports a date picker",
			"type": "boolean"
		},
		"measureConfig": {
			"description": "This is keyed by the series, e.g. 'Not operational' and determines the configuration for that series",
			"type": "object",
			"additionalProperties": {
				"type": "object",
				"properties": {
					"type": {
						"description": "How to display this series (popup-only is deprecated)",
						"enum": [
							"color",
							"icon",
							"popup-only",
							"radius",
							"shaded-spectrum",
							"shading",
							"spectrum"
						],
						"type": "string"
					},
					"measureLevel": {
						"description": "Level of the entity hierarchy that this map overlay has data for",
						"enum": [
							"Asset",
							"BesAsset",
							"BesOffice",
							"Business",
							"Case",
							"CaseContact",
							"Catchment",
							"City",
							"Commune",
							"Complaint",
							"Consumable",
							"Country",
							"Disaster",
							"District",
							"DistrictOperational",
							"Document",
							"DocumentGroup",
							"EnumerationArea",
							"Facility",
							"FacilityBuilding",
							"FacilityDivision",
							"FacilitySection",
							"Farm",
							"FetpGraduate",
							"FieldStation",
							"FijiAspenFacility",
							"HealthClinicBoundary",
							"HospitalArea",
							"HospitalWard",
							"Household",
							"Incident",
							"IncidentReported",
							"Individual",
							"Institute",
							"IrdDistrict",
							"IrdProvince",
							"IrdTehsil",
							"IrdVillage",
							"KiuarArea",
							"KiuarFacility",
							"LarvalHabitat",
							"LarvalSample",
							"LocalGovernment",
							"Maintenance",
							"MedicalArea",
							"MsupplyStore",
							"NursingZone",
							"PacmossiAsset",
							"PacmossiAssetFacility",
							"PacmossiAssetSubFacility",
							"PacmossiConsumable",
							"PacmossiConsumableBatch",
							"PacmossiDistrict",
							"PacmossiInsecticideTest",
							"PacmossiSprayingSite",
							"PacmossiVillage",
							"Pharmacy",
							"Policy",
							"Postcode",
							"Project",
							"RehabFacilityModel",
							"RepairRequest",
							"School",
							"SparePart",
							"SrhDistrict",
							"SrhSubDistrict",
							"SubCatchment",
							"SubDistrict",
							"SubFacility",
							"Supermarket",
							"TamanuCountry",
							"TmfDistrict",
							"TmfFacility",
							"TmfProject",
							"TmfSubDistrict",
							"Transfer",
							"Trap",
							"Vehicle",
							"Village",
							"VisitingSpecialist",
							"WaterSample",
							"Wholesaler",
							"WishSubDistrict",
							"World",
							"asset",
							"bes_asset",
							"bes_office",
							"business",
							"case",
							"case_contact",
							"catchment",
							"city",
							"commune",
							"complaint",
							"consumable",
							"country",
							"disaster",
							"district",
							"district_operational",
							"document",
							"document_group",
							"enumeration_area",
							"facility",
							"facility_building",
							"facility_division",
							"facility_section",
							"farm",
							"fetp_graduate",
							"field_station",
							"fiji_aspen_facility",
							"health_clinic_boundary",
							"hospital_area",
							"hospital_ward",
							"household",
							"incident",
							"incident_reported",
							"individual",
							"institute",
							"ird_district",
							"ird_province",
							"ird_tehsil",
							"ird_village",
							"kiuar_area",
							"kiuar_facility",
							"larval_habitat",
							"larval_sample",
							"local_government",
							"maintenance",
							"medical_area",
							"msupply_store",
							"nursing_zone",
							"pacmossi_asset",
							"pacmossi_asset_facility",
							"pacmossi_asset_sub_facility",
							"pacmossi_consumable",
							"pacmossi_consumable_batch",
							"pacmossi_district",
							"pacmossi_insecticide_test",
							"pacmossi_spraying_site",
							"pacmossi_village",
							"pharmacy",
							"policy",
							"postcode",
							"project",
							"rehab_facility_model",
							"repair_request",
							"school",
							"spare_part",
							"srh_district",
							"srh_sub_district",
							"sub_catchment",
							"sub_district",
							"sub_facility",
							"supermarket",
							"tamanu_country",
							"tmf_district",
							"tmf_facility",
							"tmf_project",
							"tmf_sub_district",
							"transfer",
							"trap",
							"vehicle",
							"village",
							"visiting_specialist",
							"water_sample",
							"wholesaler",
							"wish_sub_district",
							"world"
						],
						"type": "string"
					},
					"values": {
						"description": "Level of the entity hierarchy that this map overlay has data for",
						"type": "array",
						"items": {
							"type": "object",
							"properties": {
								"color": {
									"type": "string"
								},
								"hideFromLegend": {
									"description": "Whether to hide this value from the legend",
									"type": "boolean"
								},
								"hideFromPopup": {
									"description": "Whether to hide this value from the popup/tooltip",
									"type": "boolean"
								},
								"icon": {
									"description": "What icon to use for this value",
									"enum": [
										"checkbox",
										"circle",
										"downArrow",
										"empty",
										"fade",
										"h",
										"healthPin",
										"help",
										"hidden",
										"pentagon",
										"pin",
										"radius",
										"rightArrow",
										"ring",
										"square",
										"triangle",
										"upArrow",
										"warning",
										"x"
									],
									"type": "string"
								},
								"name": {
									"description": "Display name for this value",
									"type": "string"
								},
								"value": {
									"description": "The value (use 'null' to configure the behaviour for 'No data')",
									"type": [
										"string",
										"number",
										"null"
									]
								}
							},
							"additionalProperties": false,
							"required": [
								"value"
							]
						}
					},
					"sortOrder": {
						"description": "Order to show this series in the popup/tooltip",
						"type": "number"
					},
					"hideFromLegend": {
						"description": "Whether to include this series in the legend",
						"type": "boolean"
					},
					"hideFromPopup": {
						"description": "Whether to include this series in the popup/tooltip",
						"type": "boolean"
					},
					"hideFromTable": {
						"description": "Whether to include this series in the table",
						"type": "boolean"
					},
					"name": {
						"description": "Display name of this series",
						"type": "string"
					},
					"color": {
						"description": "A CSS color string e.g. green or #abc123",
						"type": "string"
					}
				},
				"additionalProperties": false,
				"required": [
					"type"
				]
			}
		},
		"measureLevel": {
			"description": "Level of the entity hierarchy that this map overlay has data for",
			"enum": [
				"Asset",
				"BesAsset",
				"BesOffice",
				"Business",
				"Case",
				"CaseContact",
				"Catchment",
				"City",
				"Commune",
				"Complaint",
				"Consumable",
				"Country",
				"Disaster",
				"District",
				"DistrictOperational",
				"Document",
				"DocumentGroup",
				"EnumerationArea",
				"Facility",
				"FacilityBuilding",
				"FacilityDivision",
				"FacilitySection",
				"Farm",
				"FetpGraduate",
				"FieldStation",
				"FijiAspenFacility",
				"HealthClinicBoundary",
				"HospitalArea",
				"HospitalWard",
				"Household",
				"Incident",
				"IncidentReported",
				"Individual",
				"Institute",
				"IrdDistrict",
				"IrdProvince",
				"IrdTehsil",
				"IrdVillage",
				"KiuarArea",
				"KiuarFacility",
				"LarvalHabitat",
				"LarvalSample",
				"LocalGovernment",
				"Maintenance",
				"MedicalArea",
				"MsupplyStore",
				"NursingZone",
				"PacmossiAsset",
				"PacmossiAssetFacility",
				"PacmossiAssetSubFacility",
				"PacmossiConsumable",
				"PacmossiConsumableBatch",
				"PacmossiDistrict",
				"PacmossiInsecticideTest",
				"PacmossiSprayingSite",
				"PacmossiVillage",
				"Pharmacy",
				"Policy",
				"Postcode",
				"Project",
				"RehabFacilityModel",
				"RepairRequest",
				"School",
				"SparePart",
				"SrhDistrict",
				"SrhSubDistrict",
				"SubCatchment",
				"SubDistrict",
				"SubFacility",
				"Supermarket",
				"TamanuCountry",
				"TmfDistrict",
				"TmfFacility",
				"TmfProject",
				"TmfSubDistrict",
				"Transfer",
				"Trap",
				"Vehicle",
				"Village",
				"VisitingSpecialist",
				"WaterSample",
				"Wholesaler",
				"WishSubDistrict",
				"World",
				"asset",
				"bes_asset",
				"bes_office",
				"business",
				"case",
				"case_contact",
				"catchment",
				"city",
				"commune",
				"complaint",
				"consumable",
				"country",
				"disaster",
				"district",
				"district_operational",
				"document",
				"document_group",
				"enumeration_area",
				"facility",
				"facility_building",
				"facility_division",
				"facility_section",
				"farm",
				"fetp_graduate",
				"field_station",
				"fiji_aspen_facility",
				"health_clinic_boundary",
				"hospital_area",
				"hospital_ward",
				"household",
				"incident",
				"incident_reported",
				"individual",
				"institute",
				"ird_district",
				"ird_province",
				"ird_tehsil",
				"ird_village",
				"kiuar_area",
				"kiuar_facility",
				"larval_habitat",
				"larval_sample",
				"local_government",
				"maintenance",
				"medical_area",
				"msupply_store",
				"nursing_zone",
				"pacmossi_asset",
				"pacmossi_asset_facility",
				"pacmossi_asset_sub_facility",
				"pacmossi_consumable",
				"pacmossi_consumable_batch",
				"pacmossi_district",
				"pacmossi_insecticide_test",
				"pacmossi_spraying_site",
				"pacmossi_village",
				"pharmacy",
				"policy",
				"postcode",
				"project",
				"rehab_facility_model",
				"repair_request",
				"school",
				"spare_part",
				"srh_district",
				"srh_sub_district",
				"sub_catchment",
				"sub_district",
				"sub_facility",
				"supermarket",
				"tamanu_country",
				"tmf_district",
				"tmf_facility",
				"tmf_project",
				"tmf_sub_district",
				"transfer",
				"trap",
				"vehicle",
				"village",
				"visiting_specialist",
				"water_sample",
				"wholesaler",
				"wish_sub_district",
				"world"
			],
			"type": "string"
		},
		"noDataColour": {
			"description": "The colour to use when there is no data",
			"type": "string"
		},
		"periodGranularity": {
			"description": "Granularity of dates in the viz. Controls the date picker and x axis granularity",
			"enum": [
				"day",
				"month",
				"one_day_at_a_time",
				"one_month_at_a_time",
				"one_quarter_at_a_time",
				"one_week_at_a_time",
				"one_year_at_a_time",
				"quarter",
				"week",
				"year"
			],
			"type": "string"
		},
		"popupHeaderFormat": {
			"description": "Format string for how each series should display in the popup/tooltip. Supports '{<columnName>}' as a substitute marker\neg. {code}: {value}",
			"type": "string"
		},
		"valueType": {
			"description": "Data format of the data in this map overlay",
			"enum": [
				"boolean",
				"currency",
				"default",
				"fraction",
				"fractionAndPercentage",
				"number",
				"numberAndPercentage",
				"oneDecimalPlace",
				"percentage",
				"text"
			],
			"type": "string"
		},
		"values": {
			"description": "Configure display options for data values",
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"color": {
						"type": "string"
					},
					"hideFromLegend": {
						"description": "Whether to hide this value from the legend",
						"type": "boolean"
					},
					"hideFromPopup": {
						"description": "Whether to hide this value from the popup/tooltip",
						"type": "boolean"
					},
					"icon": {
						"description": "What icon to use for this value",
						"enum": [
							"checkbox",
							"circle",
							"downArrow",
							"empty",
							"fade",
							"h",
							"healthPin",
							"help",
							"hidden",
							"pentagon",
							"pin",
							"radius",
							"rightArrow",
							"ring",
							"square",
							"triangle",
							"upArrow",
							"warning",
							"x"
						],
						"type": "string"
					},
					"name": {
						"description": "Display name for this value",
						"type": "string"
					},
					"value": {
						"description": "The value (use 'null' to configure the behaviour for 'No data')",
						"type": [
							"string",
							"number",
							"null"
						]
					}
				},
				"additionalProperties": false,
				"required": [
					"value"
				]
			}
		}
	},
	"additionalProperties": false
}
