/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const CamelCasedQuestionSchema = {
	"type": "object",
	"properties": {
		"text": {
			"type": "string"
		},
		"code": {
			"type": "string"
		},
		"name": {
			"type": "string"
		},
		"type": {
			"enum": [
				"Arithmetic",
				"Autocomplete",
				"Binary",
				"Checkbox",
				"CodeGenerator",
				"Condition",
				"Date",
				"DateOfData",
				"DateTime",
				"Entity",
				"File",
				"FreeText",
				"Geolocate",
				"Instruction",
				"Number",
				"Photo",
				"PrimaryEntity",
				"Radio",
				"SubmissionDate",
				"Task",
				"User"
			],
			"type": "string"
		},
		"updatedAtSyncTick": {
			"type": "string"
		},
		"dataElementId": {
			"type": "string"
		},
		"detail": {
			"type": "string"
		},
		"hook": {
			"type": "string"
		},
		"optionSetId": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"text",
		"type",
		"updatedAtSyncTick"
	]
}
