/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const CamelCasedComponentSchema = {
	"type": "object",
	"properties": {
		"updatedAtSyncTick": {
			"type": "string"
		},
		"answersEnablingFollowUp": {
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"componentNumber": {
			"type": "number"
		},
		"detailLabel": {
			"type": "string"
		},
		"isFollowUp": {
			"type": "boolean"
		},
		"questionId": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"componentNumber",
		"questionId",
		"updatedAtSyncTick"
	]
}
