/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const CartesianChartPresentationOptionsSchema = {
	"additionalProperties": false,
	"type": "object",
	"properties": {
		"exportWithLabels": {
			"description": "Include labels for each point of data in exports",
			"type": "boolean"
		},
		"exportWithTable": {
			"description": "Include the data table below the viz in exports",
			"type": "boolean"
		},
		"exportWithTableDisabled": {
			"description": "Set to 'true' to prevent users from exporting this viz with the data table",
			"type": "boolean"
		},
		"periodTickFormat": {
			"description": "This string is one of the [Moment.js format]{@link https://momentjs.com/docs/#/displaying/format/} values",
			"type": "string"
		},
		"hideAverage": {
			"description": "Hides the data average line",
			"type": "boolean"
		},
		"referenceLines": {
			"description": "Configure reference lines to appear in on the viz",
			"type": "object",
			"properties": {
				"targetLine": {
					"type": "object",
					"properties": {
						"referenceValue": {
							"description": "Value where the reference line is drawn (if not given no reference line will be drawn)",
							"type": "number"
						},
						"referenceLabel": {
							"description": "Label shown on the reference line",
							"type": "string"
						}
					},
					"additionalProperties": false,
					"required": [
						"referenceValue"
					]
				}
			},
			"additionalProperties": false
		}
	}
}
