/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const ChartReportSchema = {
	"additionalProperties": false,
	"type": "object",
	"properties": {
		"startDate": {
			"type": "string"
		},
		"endDate": {
			"type": "string"
		},
		"period": {
			"type": "object",
			"properties": {
				"earliestAvailable": {
					"type": "string"
				},
				"latestAvailable": {
					"type": "string"
				},
				"requested": {
					"type": "string"
				}
			},
			"additionalProperties": false
		},
		"type": {
			"type": "string",
			"enum": [
				"default"
			]
		},
		"data": {
			"type": "array",
			"items": {
				"description": "This is the shape of a report when type is 'chart'",
				"type": "object",
				"properties": {
					"name": {
						"type": "string"
					},
					"value": {
						"type": [
							"string",
							"number"
						]
					},
					"timestamp": {
						"type": "number"
					}
				},
				"additionalProperties": false,
				"required": [
					"value"
				]
			}
		}
	},
	"required": [
		"endDate",
		"startDate"
	]
}
