/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const ChartTypeSchema = {
	"description": "These are the common chart config options that are shared between several chart types",
	"enum": [
		"area",
		"bar",
		"composed",
		"gauge",
		"line",
		"pie"
	],
	"type": "string"
}
