/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const ChartDataSchema = {
	"description": "This is the shape of a report when type is 'chart'",
	"type": "object",
	"properties": {
		"name": {
			"type": "string"
		},
		"value": {
			"type": [
				"string",
				"number"
			]
		},
		"timestamp": {
			"type": "number"
		}
	},
	"additionalProperties": false,
	"required": [
		"value"
	]
}
