/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const ClinicUpdateSchema = {
	"type": "object",
	"properties": {
		"category_code": {
			"type": "string"
		},
		"code": {
			"type": "string"
		},
		"country_id": {
			"type": "string"
		},
		"geographical_area_id": {
			"type": "string"
		},
		"id": {
			"type": "string"
		},
		"name": {
			"type": "string"
		},
		"type": {
			"type": "string"
		},
		"type_name": {
			"type": "string"
		}
	},
	"additionalProperties": false
}
