/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const ColorPresentationOptionSchema = {
	"description": "this is keyed by value, e.g. { 'yes': { color: 'green' }, 'no': { color: 'red' } }",
	"type": "object",
	"additionalProperties": false
}
