/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const CommentSchema = {
	"type": "object",
	"properties": {
		"created_time": {
			"type": "string",
			"format": "date-time"
		},
		"id": {
			"type": "string"
		},
		"last_modified_time": {
			"type": "string",
			"format": "date-time"
		},
		"text": {
			"type": "string"
		},
		"user_id": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"created_time",
		"id",
		"last_modified_time",
		"text"
	]
}
