/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const ComposedChartConfigSchema = {
	"description": "A Composed chart is a concept from Recharts, e.g. a line chart layered on top of a bar chart",
	"additionalProperties": false,
	"type": "object",
	"properties": {
		"label": {},
		"source": {
			"description": "If specified allows the frontend to know where the data is coming from, so if there is no data it can show a custom no-data message e.g. \"Requires mSupply\".",
			"type": "string"
		},
		"color": {
			"description": "Some chart types take 'color' as an option",
			"type": "string"
		},
		"name": {
			"description": "The title of the viz",
			"type": "string"
		},
		"description": {
			"description": "A short description that appears above a viz",
			"type": "string"
		},
		"periodGranularity": {
			"description": "Granularity of dates in the viz. Controls the date picker and x axis granularity",
			"enum": [
				"day",
				"month",
				"one_day_at_a_time",
				"one_month_at_a_time",
				"one_quarter_at_a_time",
				"one_week_at_a_time",
				"one_year_at_a_time",
				"quarter",
				"week",
				"year"
			],
			"type": "string"
		},
		"dateOffset": {
			"description": "The number of periods to offset the date range by, for single date period granularities. E.g. if the period granularity is 'one_year_at_a_time' and the date offset is 6 months, the year will run from July-June. Only months and quarter offsets are supported.\nCurrently only works for 'one_year_at_a_time' and 'year' granularities -  assume that any other granularities used with this will not work as expected.",
			"type": "object",
			"properties": {
				"unit": {
					"enum": [
						"month",
						"quarter"
					],
					"type": "string"
				},
				"offset": {
					"type": "number"
				}
			},
			"additionalProperties": false,
			"required": [
				"offset",
				"unit"
			]
		},
		"defaultTimePeriod": {
			"description": "Initial date range for this viz.\nEither a single offset, or an ISO string / offset for start/end date\neg.\n// Single offset\n\"defaultTimePeriod\": {\n  \"unit\": \"week\",\n  \"offset\": 7\n}\n\n// Explicit start/end dates\n\"defaultTimePeriod\": {\n  \"start\": \"2022-10-01\",\n  \"end\": \"2023-06-30\"\n}\n\n// Start/end date offsets\n\"defaultTimePeriod\": {\n  \"start\": {\n    \"unit\": \"week\",\n    \"offset\": -52\n  },\n  \"end\": {\n    \"unit\": \"week\",\n    \"offset\": 3\n  }\n}",
			"anyOf": [
				{
					"type": "object",
					"properties": {
						"unit": {
							"description": "Time unit to offset by",
							"enum": [
								"day",
								"month",
								"quarter",
								"week",
								"year"
							],
							"type": "string"
						},
						"offset": {
							"description": "Offset distance (can be negative to offset to an earlier date)",
							"type": "number"
						},
						"modifier": {
							"description": "Used to modify the offset by either moving the date to the start/end of the modifier unit",
							"enum": [
								"end_of",
								"start_of"
							],
							"type": "string"
						},
						"modifierUnit": {
							"description": "Time unit to modify the offset by",
							"enum": [
								"day",
								"month",
								"quarter",
								"week",
								"year"
							],
							"type": "string"
						}
					},
					"additionalProperties": false,
					"required": [
						"unit"
					]
				},
				{
					"type": "object",
					"properties": {
						"start": {
							"description": "Either an ISO Date string, or an offset object",
							"anyOf": [
								{
									"type": "object",
									"properties": {
										"unit": {
											"description": "Time unit to offset by",
											"enum": [
												"day",
												"month",
												"quarter",
												"week",
												"year"
											],
											"type": "string"
										},
										"offset": {
											"description": "Offset distance (can be negative to offset to an earlier date)",
											"type": "number"
										},
										"modifier": {
											"description": "Used to modify the offset by either moving the date to the start/end of the modifier unit",
											"enum": [
												"end_of",
												"start_of"
											],
											"type": "string"
										},
										"modifierUnit": {
											"description": "Time unit to modify the offset by",
											"enum": [
												"day",
												"month",
												"quarter",
												"week",
												"year"
											],
											"type": "string"
										}
									},
									"additionalProperties": false,
									"required": [
										"unit"
									]
								},
								{
									"type": "string"
								}
							]
						},
						"end": {
							"description": "Either an ISO Date string, or an offset object",
							"anyOf": [
								{
									"type": "object",
									"properties": {
										"unit": {
											"description": "Time unit to offset by",
											"enum": [
												"day",
												"month",
												"quarter",
												"week",
												"year"
											],
											"type": "string"
										},
										"offset": {
											"description": "Offset distance (can be negative to offset to an earlier date)",
											"type": "number"
										},
										"modifier": {
											"description": "Used to modify the offset by either moving the date to the start/end of the modifier unit",
											"enum": [
												"end_of",
												"start_of"
											],
											"type": "string"
										},
										"modifierUnit": {
											"description": "Time unit to modify the offset by",
											"enum": [
												"day",
												"month",
												"quarter",
												"week",
												"year"
											],
											"type": "string"
										}
									},
									"additionalProperties": false,
									"required": [
										"unit"
									]
								},
								{
									"type": "string"
								}
							]
						}
					},
					"additionalProperties": false
				}
			]
		},
		"datePickerLimits": {
			"description": "Maximum date ranges that the date picker can be used to choose from",
			"type": "object",
			"properties": {
				"start": {
					"type": "object",
					"properties": {
						"unit": {
							"description": "Time unit to offset by",
							"enum": [
								"day",
								"month",
								"quarter",
								"week",
								"year"
							],
							"type": "string"
						},
						"offset": {
							"description": "Offset distance (can be negative to offset to an earlier date)",
							"type": "number"
						},
						"modifier": {
							"description": "Used to modify the offset by either moving the date to the start/end of the modifier unit",
							"enum": [
								"end_of",
								"start_of"
							],
							"type": "string"
						},
						"modifierUnit": {
							"description": "Time unit to modify the offset by",
							"enum": [
								"day",
								"month",
								"quarter",
								"week",
								"year"
							],
							"type": "string"
						}
					},
					"additionalProperties": false,
					"required": [
						"unit"
					]
				},
				"end": {
					"type": "object",
					"properties": {
						"unit": {
							"description": "Time unit to offset by",
							"enum": [
								"day",
								"month",
								"quarter",
								"week",
								"year"
							],
							"type": "string"
						},
						"offset": {
							"description": "Offset distance (can be negative to offset to an earlier date)",
							"type": "number"
						},
						"modifier": {
							"description": "Used to modify the offset by either moving the date to the start/end of the modifier unit",
							"enum": [
								"end_of",
								"start_of"
							],
							"type": "string"
						},
						"modifierUnit": {
							"description": "Time unit to modify the offset by",
							"enum": [
								"day",
								"month",
								"quarter",
								"week",
								"year"
							],
							"type": "string"
						}
					},
					"additionalProperties": false,
					"required": [
						"unit"
					]
				}
			},
			"additionalProperties": false
		},
		"exportConfig": {
			"description": "Extra config options for exporting",
			"type": "object",
			"properties": {
				"dataElementHeader": {
					"description": "Sets the header for the data element in xls exports",
					"type": "string"
				}
			},
			"additionalProperties": false
		},
		"noDataMessage": {
			"description": "Message which shows if no data is found",
			"type": "string"
		},
		"noDataFetch": {
			"description": "If true, Tupaia will not fetch any data for this viz. Usually used with custom vizes of type: component, e.g. ProjectDescription.",
			"default": false,
			"type": "boolean"
		},
		"drillDown": {
			"description": "Configure drill down functionality in this viz to allow clicking through to another visual",
			"type": "object",
			"properties": {
				"itemCode": {
					"description": "The code of the dashboard item that drilling down through this viz should take you to",
					"type": "string"
				},
				"keyLink": {
					"type": "string"
				},
				"parameterLink": {
					"description": "Parameter that the value which is drilled through should link to when fetching data for the drill down dashboard item",
					"type": "string"
				},
				"itemCodeByEntry": {
					"description": "A map of series codes to dashboard item codes that drilling down each series should take you to",
					"type": "object",
					"additionalProperties": {
						"type": "string"
					}
				}
			},
			"additionalProperties": false
		},
		"entityHeader": {
			"description": "",
			"type": "string"
		},
		"reference": {
			"description": "If provided shows an (i) icon next to the viz title, which allows linking to the source data",
			"anyOf": [
				{
					"description": "One of the two shapes which {@link ReferenceProps} can take.",
					"type": "object",
					"properties": {
						"text": {
							"type": "string"
						}
					},
					"additionalProperties": false,
					"required": [
						"text"
					]
				},
				{
					"description": "One of the two shapes which {@link ReferenceProps} can take.",
					"type": "object",
					"properties": {
						"name": {
							"type": "string"
						},
						"link": {
							"type": "string"
						}
					},
					"additionalProperties": false,
					"required": [
						"link",
						"name"
					]
				}
			]
		},
		"weekDisplayFormat": {
			"description": "Allows customising how weeks are displayed, e.g. 'W/C 6 Jan 2020' or 'ISO Week 2 2020'",
			"default": "'WEEK_COMMENCING_ABBR'",
			"enum": [
				"ISO_WEEK_NUMBER",
				"WEEK_COMMENCING",
				"WEEK_COMMENCING_ABBR",
				"WEEK_ENDING",
				"WEEK_ENDING_ABBR"
			],
			"type": "string"
		},
		"dateRangeDelimiter": {
			"description": "If specified, this delimiter will be used to separate the start and end dates in the date range picker. Defaults to '-'. This only applies to dates when the type is a single date but has an offset. E.g. offset of 6 months with a date range delimiter of '/' will show 'Jul 2022/June 2023'",
			"type": "string"
		},
		"type": {
			"type": "string",
			"enum": [
				"chart"
			]
		},
		"chartType": {
			"type": "string",
			"enum": [
				"composed"
			]
		},
		"ticks": {
			"description": "Array of values to show as ticks on the y axis. See: https://recharts.org/en-US/api/YAxis#ticks",
			"type": "array",
			"items": {}
		},
		"startDate": {
			"type": "string"
		},
		"endDate": {
			"type": "string"
		},
		"valueType": {
			"description": "Data type for this viz",
			"enum": [
				"boolean",
				"color",
				"currency",
				"fraction",
				"fractionAndPercentage",
				"number",
				"oneDecimalPlace",
				"percentage",
				"text",
				"view"
			],
			"type": "string"
		},
		"showPeriodRange": {
			"description": "Set to 'all' to show the 'Latest available data:' message",
			"type": "string",
			"enum": [
				"all"
			]
		},
		"labelType": {
			"description": "Some charts can have their label customised",
			"enum": [
				"fraction",
				"fractionAndPercentage",
				"number"
			],
			"type": "string"
		},
		"renderLegendForOneItem": {
			"description": "Set to true to display the legend even if there is just a single series of data",
			"type": "boolean"
		},
		"xName": {
			"description": "The label on the x-axis",
			"type": "string"
		},
		"yName": {
			"description": "The label on the y-axis",
			"type": "string"
		},
		"yAxisDomain": {
			"description": "Configuration options for the y-axis",
			"type": "object",
			"properties": {
				"max": {
					"description": "Domain configuration for the maximum y axis value.\neg.\n// Cannot be higher than 100\n{\n  type: number\n  value: 100\n}\n\n// Clamp between 50, the maximum data value, and 100\n{\n  type: clamp\n  min: 50\n  max: 100\n}\n\n// Scale the y axis to always be 10% higher than the maximum data value\n{\n  type: scale\n  value: 1.1\n}\n\n// 20 greater than the maximum data value\n{\n  type: string\n  value: datamax + 20\n}\n\nFor more options see: https://recharts.org/en-US/api/YAxis#domain",
					"type": "object",
					"properties": {
						"type": {
							"enum": [
								"clamp",
								"number",
								"scale",
								"string"
							],
							"type": "string"
						},
						"value": {
							"type": [
								"string",
								"number"
							]
						},
						"min": {
							"type": "number"
						},
						"max": {
							"type": "number"
						}
					},
					"additionalProperties": false,
					"required": [
						"type"
					]
				},
				"min": {
					"description": "Domain configuration for the minimum y axis value.\neg.\n// Cannot be lower than 0\n{\n  type: number\n  value: 0\n}\n\n// Clamp between 0, the minimum data value, and 10\n{\n  type: clamp\n  min: 0\n  max: 10\n}\n\n// Scale the y axis to always be 10% lower than the minimum data value\n{\n  type: scale\n  value: 0.9\n}\n\n// 20 less than the minimum data value\n{\n  type: string\n  value: datamin - 20\n}\n\nFor more options see: https://recharts.org/en-US/api/YAxis#domain",
					"type": "object",
					"properties": {
						"type": {
							"enum": [
								"clamp",
								"number",
								"scale",
								"string"
							],
							"type": "string"
						},
						"value": {
							"type": [
								"string",
								"number"
							]
						},
						"min": {
							"type": "number"
						},
						"max": {
							"type": "number"
						}
					},
					"additionalProperties": false,
					"required": [
						"type"
					]
				}
			},
			"additionalProperties": false,
			"required": [
				"max",
				"min"
			]
		},
		"presentationOptions": {
			"description": "Common options for configuring the chart presentation",
			"additionalProperties": false,
			"type": "object",
			"properties": {
				"exportWithLabels": {
					"description": "Include labels for each point of data in exports",
					"type": "boolean"
				},
				"exportWithTable": {
					"description": "Include the data table below the viz in exports",
					"type": "boolean"
				},
				"exportWithTableDisabled": {
					"description": "Set to 'true' to prevent users from exporting this viz with the data table",
					"type": "boolean"
				},
				"periodTickFormat": {
					"description": "This string is one of the [Moment.js format]{@link https://momentjs.com/docs/#/displaying/format/} values",
					"type": "string"
				},
				"hideAverage": {
					"description": "Hides the data average line",
					"type": "boolean"
				},
				"referenceLines": {
					"description": "Configure reference lines to appear in on the viz",
					"type": "object",
					"properties": {
						"targetLine": {
							"type": "object",
							"properties": {
								"referenceValue": {
									"description": "Value where the reference line is drawn (if not given no reference line will be drawn)",
									"type": "number"
								},
								"referenceLabel": {
									"description": "Label shown on the reference line",
									"type": "string"
								}
							},
							"additionalProperties": false,
							"required": [
								"referenceValue"
							]
						}
					},
					"additionalProperties": false
				}
			}
		},
		"chartConfig": {
			"description": "Configuration for each individual chart within this composed chart\n\neg.\n {\n   avg_rainfall: {\n     chartType: line\n     color: green\n   }\n   num_cases: {\n     chartType: bar\n     color: red\n   }\n }",
			"type": "object",
			"additionalProperties": {
				"additionalProperties": false,
				"type": "object",
				"properties": {
					"color": {
						"description": "A CSS color string e.g. green or #abc123",
						"type": "string"
					},
					"stackId": {
						"description": "For a bar chart, series which share the same stackId will be stacked atop one another",
						"type": "number"
					},
					"legendOrder": {
						"description": "What order in the legend should this series be shown",
						"type": "number"
					},
					"yAxisDomain": {
						"description": "Minimum and maximum ranges for the y axis",
						"type": "object",
						"properties": {
							"max": {
								"description": "Domain configuration for the maximum y axis value.\neg.\n// Cannot be higher than 100\n{\n  type: number\n  value: 100\n}\n\n// Clamp between 50, the maximum data value, and 100\n{\n  type: clamp\n  min: 50\n  max: 100\n}\n\n// Scale the y axis to always be 10% higher than the maximum data value\n{\n  type: scale\n  value: 1.1\n}\n\n// 20 greater than the maximum data value\n{\n  type: string\n  value: datamax + 20\n}\n\nFor more options see: https://recharts.org/en-US/api/YAxis#domain",
								"type": "object",
								"properties": {
									"type": {
										"enum": [
											"clamp",
											"number",
											"scale",
											"string"
										],
										"type": "string"
									},
									"value": {
										"type": [
											"string",
											"number"
										]
									},
									"min": {
										"type": "number"
									},
									"max": {
										"type": "number"
									}
								},
								"additionalProperties": false,
								"required": [
									"type"
								]
							},
							"min": {
								"description": "Domain configuration for the minimum y axis value.\neg.\n// Cannot be lower than 0\n{\n  type: number\n  value: 0\n}\n\n// Clamp between 0, the minimum data value, and 10\n{\n  type: clamp\n  min: 0\n  max: 10\n}\n\n// Scale the y axis to always be 10% lower than the minimum data value\n{\n  type: scale\n  value: 0.9\n}\n\n// 20 less than the minimum data value\n{\n  type: string\n  value: datamin - 20\n}\n\nFor more options see: https://recharts.org/en-US/api/YAxis#domain",
								"type": "object",
								"properties": {
									"type": {
										"enum": [
											"clamp",
											"number",
											"scale",
											"string"
										],
										"type": "string"
									},
									"value": {
										"type": [
											"string",
											"number"
										]
									},
									"min": {
										"type": "number"
									},
									"max": {
										"type": "number"
									}
								},
								"additionalProperties": false,
								"required": [
									"type"
								]
							}
						},
						"additionalProperties": false,
						"required": [
							"max",
							"min"
						]
					},
					"yAxisOrientation": {
						"description": "Which axis this the values in this series are compared against",
						"enum": [
							"left",
							"right"
						],
						"type": "string"
					},
					"hideFromLegend": {
						"description": "Whether or not this series is shown in the legend",
						"type": "boolean"
					},
					"yName": {
						"description": "The title of the Y axis",
						"type": "string"
					},
					"valueType": {
						"description": "Format of the data for this series",
						"enum": [
							"boolean",
							"color",
							"currency",
							"fraction",
							"fractionAndPercentage",
							"number",
							"oneDecimalPlace",
							"percentage",
							"text",
							"view"
						],
						"type": "string"
					},
					"label": {
						"type": "string"
					},
					"labelType": {
						"description": "Format of the label shown on hover",
						"enum": [
							"fraction",
							"fractionAndPercentage",
							"number"
						],
						"type": "string"
					},
					"opacity": {
						"description": "Opacity for this series of data on the chart. Can be ascending, descending, or a number between 0 and 1",
						"anyOf": [
							{
								"enum": [
									"ascending",
									"descending"
								],
								"type": "string"
							},
							{
								"type": "number"
							}
						]
					},
					"chartType": {
						"enum": [
							"bar",
							"line"
						],
						"type": "string"
					},
					"dot": {
						"description": "Whether the line should show a dot at each data point",
						"type": "boolean"
					},
					"connectNulls": {
						"description": "Whether to draw a connecting line between gaps in the data",
						"type": "boolean"
					},
					"strokeDasharray": {
						"description": "The pattern of dashes and gaps used to paint the line, see: https://recharts.org/en-US/api/Line#strokeDasharray",
						"type": "string"
					}
				},
				"required": [
					"chartType"
				]
			}
		}
	},
	"required": [
		"chartType",
		"name",
		"type"
	]
}
