/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const ConditionTypeSchema = {
	"enum": [
		"<",
		"<=",
		"=",
		">",
		">="
	],
	"type": "string"
}
