/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const ConditionsObjectSchema = {
	"type": "object",
	"properties": {
		"=": {
			"type": [
				"string",
				"number"
			]
		},
		">": {
			"type": [
				"string",
				"number"
			]
		},
		"<": {
			"type": [
				"string",
				"number"
			]
		},
		">=": {
			"type": [
				"string",
				"number"
			]
		},
		"<=": {
			"type": [
				"string",
				"number"
			]
		}
	},
	"additionalProperties": false
}
