/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const ConditionQuestionConfigSchema = {
	"type": "object",
	"properties": {
		"conditions": {
			"type": "object",
			"additionalProperties": {
				"type": "object",
				"properties": {
					"formula": {
						"type": "string"
					},
					"defaultValues": {
						"type": "object",
						"additionalProperties": false
					}
				},
				"additionalProperties": false,
				"required": [
					"formula"
				]
			}
		}
	},
	"additionalProperties": false,
	"required": [
		"conditions"
	]
}
