/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const CountrySchema = {
	"type": "object",
	"properties": {
		"code": {
			"type": "string"
		},
		"id": {
			"type": "string"
		},
		"name": {
			"type": "string"
		},
		"updated_at_sync_tick": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"code",
		"id",
		"name",
		"updated_at_sync_tick"
	]
}
