/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const CountriesResponseItemSchema = {
	"type": "object",
	"properties": {
		"code": {
			"type": "string"
		},
		"name": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"code",
		"name"
	]
}
