/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const CssColorSchema = {
	"description": "A CSS color string e.g. green or #abc123",
	"type": "string"
}
