/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const DashboardCreateSchema = {
	"type": "object",
	"properties": {
		"code": {
			"type": "string"
		},
		"name": {
			"type": "string"
		},
		"root_entity_code": {
			"type": "string"
		},
		"sort_order": {
			"type": "number"
		}
	},
	"additionalProperties": false,
	"required": [
		"code",
		"name",
		"root_entity_code"
	]
}
