/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const DashboardMailingListUpdateSchema = {
	"type": "object",
	"properties": {
		"admin_permission_groups": {
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"dashboard_id": {
			"type": "string"
		},
		"entity_id": {
			"type": "string"
		},
		"id": {
			"type": "string"
		},
		"project_id": {
			"type": "string"
		}
	},
	"additionalProperties": false
}
