/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const DashboardMailingListEntryCreateSchema = {
	"type": "object",
	"properties": {
		"dashboard_mailing_list_id": {
			"type": "string"
		},
		"email": {
			"type": "string"
		},
		"subscribed": {
			"type": "boolean"
		},
		"unsubscribed_time": {
			"type": "string",
			"format": "date-time"
		}
	},
	"additionalProperties": false,
	"required": [
		"dashboard_mailing_list_id",
		"email"
	]
}
