/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const DashboardItemTypeSchema = {
	"enum": [
		"chart",
		"component",
		"matrix",
		"view"
	],
	"type": "string"
}
