/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const DashboardItemReportSchema = {
	"anyOf": [
		{
			"additionalProperties": false,
			"type": "object",
			"properties": {
				"startDate": {
					"type": "string"
				},
				"endDate": {
					"type": "string"
				},
				"period": {
					"type": "object",
					"properties": {
						"earliestAvailable": {
							"type": "string"
						},
						"latestAvailable": {
							"type": "string"
						},
						"requested": {
							"type": "string"
						}
					},
					"additionalProperties": false
				},
				"type": {
					"enum": [
						"default",
						"rawDataExport"
					],
					"type": "string"
				},
				"data": {
					"type": "array",
					"items": {
						"anyOf": [
							{
								"type": "object",
								"properties": {
									"uniqueFileName": {
										"type": "string"
									},
									"label": {
										"type": "string"
									}
								},
								"additionalProperties": false,
								"required": [
									"label",
									"uniqueFileName"
								]
							},
							{
								"additionalProperties": false,
								"type": "object",
								"properties": {
									"value": {},
									"total": {
										"type": "number"
									},
									"viewType": {
										"enum": [
											"dataDownload",
											"filesDownload",
											"multiPhotograph",
											"multiSingleValue",
											"multiValue",
											"multiValueRow",
											"qrCodeVisual",
											"singleDate",
											"singleDownloadLink",
											"singleValue"
										],
										"type": "string"
									},
									"label": {
										"type": "string"
									}
								}
							}
						]
					}
				},
				"downloadUrl": {
					"type": "string"
				}
			},
			"required": [
				"endDate",
				"startDate"
			]
		},
		{
			"additionalProperties": false,
			"type": "object",
			"properties": {
				"type": {
					"type": "string",
					"enum": [
						"matrix"
					]
				},
				"startDate": {
					"type": "string"
				},
				"endDate": {
					"type": "string"
				},
				"period": {
					"type": "object",
					"properties": {
						"earliestAvailable": {
							"type": "string"
						},
						"latestAvailable": {
							"type": "string"
						},
						"requested": {
							"type": "string"
						}
					},
					"additionalProperties": false
				},
				"columns": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/MatrixReportColumn"
					}
				},
				"rows": {
					"type": "array",
					"items": {
						"additionalProperties": false,
						"type": "object",
						"properties": {
							"dataElement": {
								"anyOf": [
									{
										"type": "object",
										"properties": {
											"entityCode": {
												"type": "string"
											},
											"entityLabel": {
												"type": "string"
											}
										},
										"additionalProperties": false,
										"required": [
											"entityCode",
											"entityLabel"
										]
									},
									{
										"type": "string"
									}
								]
							},
							"categoryId": {
								"type": "string"
							},
							"category": {
								"type": "string"
							},
							"valueType": {
								"enum": [
									"boolean",
									"color",
									"currency",
									"fraction",
									"fractionAndPercentage",
									"number",
									"oneDecimalPlace",
									"percentage",
									"text",
									"view"
								],
								"type": "string"
							}
						}
					}
				}
			},
			"required": [
				"endDate",
				"startDate"
			]
		},
		{
			"additionalProperties": false,
			"type": "object",
			"properties": {
				"startDate": {
					"type": "string"
				},
				"endDate": {
					"type": "string"
				},
				"period": {
					"type": "object",
					"properties": {
						"earliestAvailable": {
							"type": "string"
						},
						"latestAvailable": {
							"type": "string"
						},
						"requested": {
							"type": "string"
						}
					},
					"additionalProperties": false
				},
				"type": {
					"type": "string",
					"enum": [
						"default"
					]
				},
				"data": {
					"type": "array",
					"items": {
						"description": "This is the shape of a report when type is 'chart'",
						"type": "object",
						"properties": {
							"name": {
								"type": "string"
							},
							"value": {
								"type": [
									"string",
									"number"
								]
							},
							"timestamp": {
								"type": "number"
							}
						},
						"additionalProperties": false,
						"required": [
							"value"
						]
					}
				}
			},
			"required": [
				"endDate",
				"startDate"
			]
		}
	]
}
