/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const DataElementDataGroupSchema = {
	"type": "object",
	"properties": {
		"data_element_id": {
			"type": "string"
		},
		"data_group_id": {
			"type": "string"
		},
		"id": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"data_element_id",
		"data_group_id",
		"id"
	]
}
