/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const DataServiceEntityConfigSchema = {
	"type": "object",
	"properties": {
		"dhis_id": {
			"type": "string"
		},
		"kobo_id": {
			"type": "string"
		}
	},
	"additionalProperties": false
}
