/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const DatatrakSessionCreateSchema = {
	"type": "object",
	"properties": {
		"access_policy": {
			"type": "object",
			"properties": {}
		},
		"access_token": {
			"type": "string"
		},
		"access_token_expiry": {
			"type": "string"
		},
		"email": {
			"type": "string"
		},
		"refresh_token": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"access_policy",
		"access_token",
		"access_token_expiry",
		"email",
		"refresh_token"
	]
}
