/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const DataElementConfigSchema = {
	"type": "object",
	"properties": {
		"categoryOptionCombo": {
			"type": "string"
		},
		"dataElementCode": {
			"type": "string"
		},
		"dhisDataType": {
			"enum": [
				"DataElement",
				"Indicator",
				"ProgramIndicator"
			],
			"type": "string"
		},
		"dhisId": {
			"type": "string"
		},
		"dhisInstanceCode": {
			"type": "string"
		},
		"indicator": {
			"type": "object",
			"properties": {
				"dataPeriodType": {
					"enum": [
						"DAY",
						"MONTH",
						"QUARTER",
						"WEEK",
						"YEAR"
					],
					"type": "string"
				}
			},
			"additionalProperties": false,
			"required": [
				"dataPeriodType"
			]
		}
	},
	"additionalProperties": false
}
