/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const DataElementDataServiceSchema = {
	"type": "object",
	"properties": {
		"country_code": {
			"type": "string"
		},
		"data_element_code": {
			"type": "string"
		},
		"id": {
			"type": "string"
		},
		"service_config": {
			"type": "object",
			"properties": {}
		},
		"service_type": {
			"enum": [
				"data-lake",
				"dhis",
				"indicator",
				"kobo",
				"superset",
				"tupaia",
				"weather"
			],
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"country_code",
		"data_element_code",
		"id",
		"service_config",
		"service_type"
	]
}
