/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const DataGroupCreateSchema = {
	"type": "object",
	"properties": {
		"code": {
			"type": "string"
		},
		"config": {
			"type": "object",
			"properties": {}
		},
		"service_type": {
			"enum": [
				"data-lake",
				"dhis",
				"indicator",
				"kobo",
				"superset",
				"tupaia",
				"weather"
			],
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"code",
		"service_type"
	]
}
