/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const DataSourceTypeSchema = {
	"enum": [
		"dataElement",
		"dataGroup"
	],
	"type": "string"
}
