/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const DatatrakSessionUpdateSchema = {
	"type": "object",
	"properties": {
		"access_policy": {
			"type": "object",
			"properties": {}
		},
		"access_token": {
			"type": "string"
		},
		"access_token_expiry": {
			"type": "string"
		},
		"email": {
			"type": "string"
		},
		"id": {
			"type": "string"
		},
		"refresh_token": {
			"type": "string"
		}
	},
	"additionalProperties": false
}
