/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const DataServiceSyncGroupUpdateSchema = {
	"type": "object",
	"properties": {
		"code": {
			"type": "string"
		},
		"config": {
			"type": "object",
			"properties": {}
		},
		"data_group_code": {
			"type": "string"
		},
		"id": {
			"type": "string"
		},
		"service_type": {
			"enum": [
				"data-lake",
				"dhis",
				"indicator",
				"kobo",
				"superset",
				"tupaia",
				"weather"
			],
			"type": "string"
		},
		"sync_cursor": {
			"type": "string"
		},
		"sync_status": {
			"enum": [
				"ERROR",
				"IDLE",
				"SYNCING"
			],
			"type": "string"
		}
	},
	"additionalProperties": false
}
