/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const DataTableTypeSchema = {
	"enum": [
		"analytics",
		"data_element_metadata",
		"data_group_metadata",
		"entities",
		"entity_attributes",
		"entity_relations",
		"events",
		"sql",
		"survey_responses"
	],
	"type": "string"
}
