/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const DataElementDataServiceUpdateSchema = {
	"type": "object",
	"properties": {
		"country_code": {
			"type": "string"
		},
		"data_element_code": {
			"type": "string"
		},
		"id": {
			"type": "string"
		},
		"service_config": {
			"type": "object",
			"properties": {}
		},
		"service_type": {
			"enum": [
				"data-lake",
				"dhis",
				"indicator",
				"kobo",
				"superset",
				"tupaia",
				"weather"
			],
			"type": "string"
		}
	},
	"additionalProperties": false
}
