/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const DataTableCreateSchema = {
	"type": "object",
	"properties": {
		"code": {
			"type": "string"
		},
		"config": {
			"type": "object",
			"properties": {}
		},
		"description": {
			"type": "string"
		},
		"permission_groups": {
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"type": {
			"enum": [
				"analytics",
				"data_element_metadata",
				"data_group_metadata",
				"entities",
				"entity_attributes",
				"entity_relations",
				"events",
				"sql",
				"survey_responses"
			],
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"code",
		"permission_groups",
		"type"
	]
}
