/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const DataServiceEntitySchema = {
	"type": "object",
	"properties": {
		"config": {
			"type": "object",
			"properties": {
				"dhis_id": {
					"type": "string"
				},
				"kobo_id": {
					"type": "string"
				}
			},
			"additionalProperties": false
		},
		"entity_code": {
			"type": "string"
		},
		"id": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"config",
		"entity_code",
		"id"
	]
}
