/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const DatePickerOffsetSpecSchema = {
	"type": "object",
	"properties": {
		"unit": {
			"enum": [
				"month",
				"quarter"
			],
			"type": "string"
		},
		"offset": {
			"type": "number"
		}
	},
	"additionalProperties": false,
	"required": [
		"offset",
		"unit"
	]
}
