/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const DateOffsetSpecSchema = {
	"type": "object",
	"properties": {
		"unit": {
			"description": "Time unit to offset by",
			"enum": [
				"day",
				"month",
				"quarter",
				"week",
				"year"
			],
			"type": "string"
		},
		"offset": {
			"description": "Offset distance (can be negative to offset to an earlier date)",
			"type": "number"
		},
		"modifier": {
			"description": "Used to modify the offset by either moving the date to the start/end of the modifier unit",
			"enum": [
				"end_of",
				"start_of"
			],
			"type": "string"
		},
		"modifierUnit": {
			"description": "Time unit to modify the offset by",
			"enum": [
				"day",
				"month",
				"quarter",
				"week",
				"year"
			],
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"unit"
	]
}
