/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const DebugLogUpdateSchema = {
	"type": "object",
	"properties": {
		"id": {
			"type": "string"
		},
		"info": {
			"type": "object",
			"properties": {}
		},
		"type": {
			"type": "string"
		}
	},
	"additionalProperties": false
}
