/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const DhisSyncQueueUpdateSchema = {
	"type": "object",
	"properties": {
		"bad_request_count": {
			"type": "number"
		},
		"change_time": {
			"type": "number"
		},
		"details": {
			"type": "string"
		},
		"id": {
			"type": "string"
		},
		"is_dead_letter": {
			"type": "boolean"
		},
		"is_deleted": {
			"type": "boolean"
		},
		"priority": {
			"type": "number"
		},
		"record_id": {
			"type": "string"
		},
		"record_type": {
			"type": "string"
		},
		"type": {
			"type": "string"
		}
	},
	"additionalProperties": false
}
