/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const DhisInstanceUpdateSchema = {
	"type": "object",
	"properties": {
		"code": {
			"type": "string"
		},
		"config": {
			"type": "object",
			"properties": {}
		},
		"id": {
			"type": "string"
		},
		"readonly": {
			"type": "boolean"
		}
	},
	"additionalProperties": false
}
