/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const DhisInstanceCreateSchema = {
	"type": "object",
	"properties": {
		"code": {
			"type": "string"
		},
		"config": {
			"type": "object",
			"properties": {}
		},
		"readonly": {
			"type": "boolean"
		}
	},
	"additionalProperties": false,
	"required": [
		"code",
		"config",
		"readonly"
	]
}
