/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const DhisSyncLogCreateSchema = {
	"type": "object",
	"properties": {
		"data": {
			"type": "string"
		},
		"deleted": {
			"type": "number"
		},
		"dhis_reference": {
			"type": "string"
		},
		"error_list": {
			"type": "string"
		},
		"ignored": {
			"type": "number"
		},
		"imported": {
			"type": "number"
		},
		"record_id": {
			"type": "string"
		},
		"record_type": {
			"type": "string"
		},
		"updated": {
			"type": "number"
		}
	},
	"additionalProperties": false,
	"required": [
		"record_id",
		"record_type"
	]
}
