/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const DisplayedValueTypeSchema = {
	"enum": [
		"facilityTypeName",
		"name",
		"originalValue",
		"schoolTypeName"
	],
	"type": "string"
}
