/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const DownloadFilesVisualDataItemSchema = {
	"type": "object",
	"properties": {
		"uniqueFileName": {
			"type": "string"
		},
		"label": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"label",
		"uniqueFileName"
	]
}
