/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const DraftSurveyResponseSchema = {
	"type": "object",
	"properties": {
		"id": {
			"type": "string"
		},
		"surveyId": {
			"type": "string"
		},
		"surveyCode": {
			"type": "string"
		},
		"surveyName": {
			"type": "string"
		},
		"countryCode": {
			"type": "string"
		},
		"countryName": {
			"type": "string"
		},
		"entityId": {
			"type": "string"
		},
		"entityName": {
			"type": "string"
		},
		"startTime": {
			"type": "string",
			"format": "date-time"
		},
		"formData": {
			"additionalProperties": true,
			"type": "object"
		},
		"screenNumber": {
			"type": "number"
		},
		"updatedAt": {
			"type": "string",
			"format": "date-time"
		}
	},
	"additionalProperties": false,
	"required": [
		"countryCode",
		"countryName",
		"entityId",
		"entityName",
		"formData",
		"id",
		"screenNumber",
		"startTime",
		"surveyCode",
		"surveyId",
		"surveyName",
		"updatedAt"
	]
}
