/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const EntityParentChildRelationSchema = {
	"type": "object",
	"properties": {
		"child_id": {
			"type": "string"
		},
		"entity_hierarchy_id": {
			"type": "string"
		},
		"id": {
			"type": "string"
		},
		"parent_id": {
			"type": "string"
		},
		"updated_at_sync_tick": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"child_id",
		"entity_hierarchy_id",
		"id",
		"parent_id",
		"updated_at_sync_tick"
	]
}
