/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const EntityResponseSchema = {
	"type": "object",
	"properties": {
		"attributes": {
			"type": "object",
			"properties": {
				"type": {
					"type": "string"
				}
			},
			"additionalProperties": false
		},
		"bounds": {
			"type": "string"
		},
		"code": {
			"type": "string"
		},
		"countryCode": {
			"type": "string"
		},
		"id": {
			"type": "string"
		},
		"imageUrl": {
			"type": "string"
		},
		"metadata": {
			"type": "object",
			"properties": {
				"dhis": {
					"type": "object",
					"properties": {
						"dhisInstanceCode": {
							"type": "string"
						},
						"isDataRegional": {
							"type": "boolean"
						},
						"push": {
							"type": "boolean"
						},
						"trackedEntityId": {
							"type": "string"
						}
					},
					"additionalProperties": false
				},
				"ms1": {
					"type": "object",
					"properties": {
						"distributionId": {
							"type": "string"
						}
					},
					"additionalProperties": false
				},
				"openStreetMaps": {
					"type": "object",
					"properties": {
						"id": {
							"type": "string"
						}
					},
					"additionalProperties": false
				}
			},
			"additionalProperties": false
		},
		"name": {
			"type": "string"
		},
		"parentId": {
			"type": "string"
		},
		"point": {
			"type": "string"
		},
		"region": {
			"type": "string"
		},
		"type": {
			"enum": [
				"asset",
				"bes_asset",
				"bes_office",
				"business",
				"case",
				"case_contact",
				"catchment",
				"city",
				"commune",
				"complaint",
				"consumable",
				"country",
				"disaster",
				"district",
				"district_operational",
				"document",
				"document_group",
				"enumeration_area",
				"facility",
				"facility_building",
				"facility_division",
				"facility_section",
				"farm",
				"fetp_graduate",
				"field_station",
				"fiji_aspen_facility",
				"health_clinic_boundary",
				"hospital_area",
				"hospital_ward",
				"household",
				"incident",
				"incident_reported",
				"individual",
				"institute",
				"ird_district",
				"ird_province",
				"ird_tehsil",
				"ird_village",
				"kiuar_area",
				"kiuar_facility",
				"larval_habitat",
				"larval_sample",
				"local_government",
				"maintenance",
				"medical_area",
				"msupply_store",
				"nursing_zone",
				"pacmossi_asset",
				"pacmossi_asset_facility",
				"pacmossi_asset_sub_facility",
				"pacmossi_consumable",
				"pacmossi_consumable_batch",
				"pacmossi_district",
				"pacmossi_insecticide_test",
				"pacmossi_spraying_site",
				"pacmossi_village",
				"pharmacy",
				"policy",
				"postcode",
				"project",
				"rehab_facility_model",
				"repair_request",
				"school",
				"spare_part",
				"srh_district",
				"srh_sub_district",
				"sub_catchment",
				"sub_district",
				"sub_facility",
				"supermarket",
				"tamanu_country",
				"tmf_district",
				"tmf_facility",
				"tmf_project",
				"tmf_sub_district",
				"transfer",
				"trap",
				"vehicle",
				"village",
				"visiting_specialist",
				"water_sample",
				"wholesaler",
				"wish_sub_district",
				"world"
			],
			"type": "string"
		},
		"updatedAtSyncTick": {
			"type": "string"
		},
		"isRecent": {
			"type": "boolean"
		},
		"parentName": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"attributes",
		"code",
		"id",
		"metadata",
		"name",
		"type",
		"updatedAtSyncTick"
	]
}
