/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const EntityParentChildRelationUpdateSchema = {
	"type": "object",
	"properties": {
		"child_id": {
			"type": "string"
		},
		"entity_hierarchy_id": {
			"type": "string"
		},
		"id": {
			"type": "string"
		},
		"parent_id": {
			"type": "string"
		}
	},
	"additionalProperties": false
}
