/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const EntityAttributesSchema = {
	"additionalProperties": false,
	"type": "object",
	"properties": {
		"type": {
			"type": "string"
		}
	}
}
