/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const EntityHierarchyUpdateSchema = {
	"type": "object",
	"properties": {
		"canonical_types": {
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"id": {
			"type": "string"
		},
		"name": {
			"type": "string"
		}
	},
	"additionalProperties": false
}
