/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const EntityHierarchySchema = {
	"type": "object",
	"properties": {
		"canonical_types": {
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"id": {
			"type": "string"
		},
		"name": {
			"type": "string"
		},
		"updated_at_sync_tick": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"id",
		"name",
		"updated_at_sync_tick"
	]
}
