/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const EntityMetadataSchema = {
	"type": "object",
	"properties": {
		"dhis": {
			"type": "object",
			"properties": {
				"dhisInstanceCode": {
					"type": "string"
				},
				"isDataRegional": {
					"type": "boolean"
				},
				"push": {
					"type": "boolean"
				},
				"trackedEntityId": {
					"type": "string"
				}
			},
			"additionalProperties": false
		},
		"ms1": {
			"type": "object",
			"properties": {
				"distributionId": {
					"type": "string"
				}
			},
			"additionalProperties": false
		},
		"openStreetMaps": {
			"type": "object",
			"properties": {
				"id": {
					"type": "string"
				}
			},
			"additionalProperties": false
		}
	},
	"additionalProperties": false
}
