/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const EntityQuestionConfigFieldsSchema = {
	"enum": [
		"attributes",
		"code",
		"country_code",
		"id",
		"image_url",
		"metadata",
		"name",
		"type",
		"updated_at_sync_tick"
	],
	"type": "string"
}
