/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const ErrorLogCreateSchema = {
	"type": "object",
	"properties": {
		"api_request_log_id": {
			"type": "string"
		},
		"error_time": {
			"type": "string",
			"format": "date-time"
		},
		"message": {
			"type": "string"
		},
		"type": {
			"type": "string"
		}
	},
	"additionalProperties": false
}
