/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const ErrorLogSchema = {
	"type": "object",
	"properties": {
		"api_request_log_id": {
			"type": "string"
		},
		"error_time": {
			"type": "string",
			"format": "date-time"
		},
		"id": {
			"type": "string"
		},
		"message": {
			"type": "string"
		},
		"type": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"id"
	]
}
