/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const ExportPresentationOptionsSchema = {
	"type": "object",
	"properties": {
		"exportWithLabels": {
			"description": "Include labels for each point of data in exports",
			"type": "boolean"
		},
		"exportWithTable": {
			"description": "Include the data table below the viz in exports",
			"type": "boolean"
		},
		"exportWithTableDisabled": {
			"description": "Set to 'true' to prevent users from exporting this viz with the data table",
			"type": "boolean"
		}
	},
	"additionalProperties": false
}
