/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const ExternalDatabaseConnectionSchema = {
	"type": "object",
	"properties": {
		"code": {
			"type": "string"
		},
		"description": {
			"type": "string"
		},
		"id": {
			"type": "string"
		},
		"name": {
			"type": "string"
		},
		"permission_groups": {
			"type": "array",
			"items": {
				"type": "string"
			}
		}
	},
	"additionalProperties": false,
	"required": [
		"code",
		"id",
		"name",
		"permission_groups"
	]
}
