/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const FeedItemSchema = {
	"type": "object",
	"properties": {
		"country_id": {
			"type": "string"
		},
		"creation_date": {
			"type": "string",
			"format": "date-time"
		},
		"geographical_area_id": {
			"type": "string"
		},
		"id": {
			"type": "string"
		},
		"permission_group_id": {
			"type": "string"
		},
		"record_id": {
			"type": "string"
		},
		"template_variables": {
			"type": "object",
			"properties": {
				"constructor": {
					"$ref": "#/definitions/Function"
				}
			},
			"additionalProperties": false,
			"required": [
				"constructor"
			]
		},
		"type": {
			"enum": [
				"SurveyResponse",
				"markdown"
			],
			"type": "string"
		},
		"user_id": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"id"
	]
}
