/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const FrontEndExcludedConfigSchema = {
	"type": "object",
	"properties": {
		"types": {
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"exceptions": {
			"type": "object",
			"properties": {
				"permissionGroups": {
					"type": "array",
					"items": {
						"type": "string"
					}
				}
			},
			"additionalProperties": false,
			"required": [
				"permissionGroups"
			]
		}
	},
	"additionalProperties": false,
	"required": [
		"types"
	]
}
