/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const FrontEndExcludedExceptionSchema = {
	"type": "object",
	"properties": {
		"permissionGroups": {
			"type": "array",
			"items": {
				"type": "string"
			}
		}
	},
	"additionalProperties": false,
	"required": [
		"permissionGroups"
	]
}
