/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const GeographicalAreaUpdateSchema = {
	"type": "object",
	"properties": {
		"code": {
			"type": "string"
		},
		"country_id": {
			"type": "string"
		},
		"id": {
			"type": "string"
		},
		"level_code": {
			"type": "string"
		},
		"level_name": {
			"type": "string"
		},
		"name": {
			"type": "string"
		},
		"parent_id": {
			"type": "string"
		}
	},
	"additionalProperties": false
}
