/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const IconKeySchema = {
	"enum": [
		"checkbox",
		"circle",
		"downArrow",
		"empty",
		"fade",
		"h",
		"healthPin",
		"help",
		"hidden",
		"pentagon",
		"pin",
		"radius",
		"rightArrow",
		"ring",
		"square",
		"triangle",
		"upArrow",
		"warning",
		"x"
	],
	"type": "string"
}
