/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const IndicatorCreateSchema = {
	"type": "object",
	"properties": {
		"builder": {
			"type": "string"
		},
		"code": {
			"type": "string"
		},
		"config": {
			"type": "object",
			"properties": {}
		}
	},
	"additionalProperties": false,
	"required": [
		"builder",
		"code"
	]
}
