/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const InlineValueSchema = {
	"type": "object",
	"properties": {
		"color": {
			"type": "string"
		},
		"hideFromLegend": {
			"description": "Whether to hide this value from the legend",
			"type": "boolean"
		},
		"hideFromPopup": {
			"description": "Whether to hide this value from the popup/tooltip",
			"type": "boolean"
		},
		"icon": {
			"description": "What icon to use for this value",
			"enum": [
				"checkbox",
				"circle",
				"downArrow",
				"empty",
				"fade",
				"h",
				"healthPin",
				"help",
				"hidden",
				"pentagon",
				"pin",
				"radius",
				"rightArrow",
				"ring",
				"square",
				"triangle",
				"upArrow",
				"warning",
				"x"
			],
			"type": "string"
		},
		"name": {
			"description": "Display name for this value",
			"type": "string"
		},
		"value": {
			"description": "The value (use 'null' to configure the behaviour for 'No data')",
			"type": [
				"string",
				"number",
				"null"
			]
		}
	},
	"additionalProperties": false,
	"required": [
		"value"
	]
}
