/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const LandingPageCreateSchema = {
	"type": "object",
	"properties": {
		"contact_us": {
			"type": "string"
		},
		"extended_title": {
			"type": "string"
		},
		"external_link": {
			"type": "string"
		},
		"image_url": {
			"type": "string"
		},
		"include_name_in_header": {
			"type": "boolean"
		},
		"logo_url": {
			"type": "string"
		},
		"long_bio": {
			"type": "string"
		},
		"name": {
			"type": "string"
		},
		"phone_number": {
			"type": "string"
		},
		"primary_hexcode": {
			"type": "string"
		},
		"project_codes": {
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"secondary_hexcode": {
			"type": "string"
		},
		"url_segment": {
			"type": "string"
		},
		"website_url": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"name",
		"url_segment"
	]
}
