/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const LeaderboardItemSchema = {
	"type": "object",
	"properties": {
		"user_id": {
			"type": "string"
		},
		"first_name": {
			"type": "string"
		},
		"last_name": {
			"type": "string"
		},
		"coconuts": {
			"type": "number"
		},
		"pigs": {
			"type": "number"
		}
	},
	"additionalProperties": false,
	"required": [
		"coconuts",
		"first_name",
		"last_name",
		"pigs",
		"user_id"
	]
}
