/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const LegacyReportSchema = {
	"type": "object",
	"properties": {
		"code": {
			"type": "string"
		},
		"data_builder": {
			"type": "string"
		},
		"data_builder_config": {
			"type": "object",
			"properties": {}
		},
		"data_services": {
			"type": "object",
			"properties": {}
		},
		"id": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"code",
		"id"
	]
}
