/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const LineChartChartConfigSchema = {
	"additionalProperties": false,
	"type": "object",
	"properties": {
		"color": {
			"description": "A CSS color string e.g. green or #abc123",
			"type": "string"
		},
		"stackId": {
			"description": "For a bar chart, series which share the same stackId will be stacked atop one another",
			"type": "number"
		},
		"legendOrder": {
			"description": "What order in the legend should this series be shown",
			"type": "number"
		},
		"yAxisDomain": {
			"description": "Minimum and maximum ranges for the y axis",
			"type": "object",
			"properties": {
				"max": {
					"description": "Domain configuration for the maximum y axis value.\neg.\n// Cannot be higher than 100\n{\n  type: number\n  value: 100\n}\n\n// Clamp between 50, the maximum data value, and 100\n{\n  type: clamp\n  min: 50\n  max: 100\n}\n\n// Scale the y axis to always be 10% higher than the maximum data value\n{\n  type: scale\n  value: 1.1\n}\n\n// 20 greater than the maximum data value\n{\n  type: string\n  value: datamax + 20\n}\n\nFor more options see: https://recharts.org/en-US/api/YAxis#domain",
					"type": "object",
					"properties": {
						"type": {
							"enum": [
								"clamp",
								"number",
								"scale",
								"string"
							],
							"type": "string"
						},
						"value": {
							"type": [
								"string",
								"number"
							]
						},
						"min": {
							"type": "number"
						},
						"max": {
							"type": "number"
						}
					},
					"additionalProperties": false,
					"required": [
						"type"
					]
				},
				"min": {
					"description": "Domain configuration for the minimum y axis value.\neg.\n// Cannot be lower than 0\n{\n  type: number\n  value: 0\n}\n\n// Clamp between 0, the minimum data value, and 10\n{\n  type: clamp\n  min: 0\n  max: 10\n}\n\n// Scale the y axis to always be 10% lower than the minimum data value\n{\n  type: scale\n  value: 0.9\n}\n\n// 20 less than the minimum data value\n{\n  type: string\n  value: datamin - 20\n}\n\nFor more options see: https://recharts.org/en-US/api/YAxis#domain",
					"type": "object",
					"properties": {
						"type": {
							"enum": [
								"clamp",
								"number",
								"scale",
								"string"
							],
							"type": "string"
						},
						"value": {
							"type": [
								"string",
								"number"
							]
						},
						"min": {
							"type": "number"
						},
						"max": {
							"type": "number"
						}
					},
					"additionalProperties": false,
					"required": [
						"type"
					]
				}
			},
			"additionalProperties": false,
			"required": [
				"max",
				"min"
			]
		},
		"yAxisOrientation": {
			"description": "Which axis this the values in this series are compared against",
			"enum": [
				"left",
				"right"
			],
			"type": "string"
		},
		"hideFromLegend": {
			"description": "Whether or not this series is shown in the legend",
			"type": "boolean"
		},
		"yName": {
			"description": "The title of the Y axis",
			"type": "string"
		},
		"valueType": {
			"description": "Format of the data for this series",
			"enum": [
				"boolean",
				"color",
				"currency",
				"fraction",
				"fractionAndPercentage",
				"number",
				"oneDecimalPlace",
				"percentage",
				"text",
				"view"
			],
			"type": "string"
		},
		"label": {
			"type": "string"
		},
		"labelType": {
			"description": "Format of the label shown on hover",
			"enum": [
				"fraction",
				"fractionAndPercentage",
				"number"
			],
			"type": "string"
		},
		"opacity": {
			"description": "Opacity for this series of data on the chart. Can be ascending, descending, or a number between 0 and 1",
			"anyOf": [
				{
					"enum": [
						"ascending",
						"descending"
					],
					"type": "string"
				},
				{
					"type": "number"
				}
			]
		},
		"chartType": {
			"description": "These are the common chart config options that are shared between several chart types",
			"enum": [
				"area",
				"bar",
				"composed",
				"gauge",
				"line",
				"pie"
			],
			"type": "string"
		},
		"dot": {
			"description": "Whether the line should show a dot at each data point",
			"type": "boolean"
		},
		"connectNulls": {
			"description": "Whether to draw a connecting line between gaps in the data",
			"type": "boolean"
		},
		"strokeDasharray": {
			"description": "The pattern of dashes and gaps used to paint the line, see: https://recharts.org/en-US/api/Line#strokeDasharray",
			"type": "string"
		}
	}
}
