/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const LinkReferencePropsSchema = {
	"description": "One of the two shapes which {@link ReferenceProps} can take.",
	"type": "object",
	"properties": {
		"name": {
			"type": "string"
		},
		"link": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"link",
		"name"
	]
}
