/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const LoginAttemptsUpdateSchema = {
	"type": "object",
	"properties": {
		"expire": {
			"type": "string"
		},
		"key": {
			"type": "string"
		},
		"points": {
			"type": "number"
		}
	},
	"additionalProperties": false
}
