/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const LoginAttemptsCreateSchema = {
	"type": "object",
	"properties": {
		"expire": {
			"type": "string"
		},
		"key": {
			"type": "string"
		},
		"points": {
			"type": "number"
		}
	},
	"additionalProperties": false,
	"required": [
		"key"
	]
}
