/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const MailingListSchema = {
	"type": "object",
	"properties": {
		"entityCode": {
			"type": "string"
		},
		"isSubscribed": {
			"type": "boolean"
		},
		"isAdmin": {
			"type": "boolean"
		}
	},
	"additionalProperties": false,
	"required": [
		"entityCode",
		"isAdmin",
		"isSubscribed"
	]
}
