/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const MapOverlayGroupRelationCreateSchema = {
	"type": "object",
	"properties": {
		"child_id": {
			"type": "string"
		},
		"child_type": {
			"type": "string"
		},
		"map_overlay_group_id": {
			"type": "string"
		},
		"sort_order": {
			"type": "number"
		}
	},
	"additionalProperties": false,
	"required": [
		"child_id",
		"child_type",
		"map_overlay_group_id"
	]
}
