/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const MapOverlayGroupRelationUpdateSchema = {
	"type": "object",
	"properties": {
		"child_id": {
			"type": "string"
		},
		"child_type": {
			"type": "string"
		},
		"id": {
			"type": "string"
		},
		"map_overlay_group_id": {
			"type": "string"
		},
		"sort_order": {
			"type": "number"
		}
	},
	"additionalProperties": false
}
