/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const MapOverlayGroupUpdateSchema = {
	"type": "object",
	"properties": {
		"code": {
			"type": "string"
		},
		"id": {
			"type": "string"
		},
		"name": {
			"type": "string"
		}
	},
	"additionalProperties": false
}
