/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const MatrixReportRowSchema = {
	"additionalProperties": false,
	"type": "object",
	"properties": {
		"dataElement": {
			"anyOf": [
				{
					"type": "object",
					"properties": {
						"entityCode": {
							"type": "string"
						},
						"entityLabel": {
							"type": "string"
						}
					},
					"additionalProperties": false,
					"required": [
						"entityCode",
						"entityLabel"
					]
				},
				{
					"type": "string"
				}
			]
		},
		"categoryId": {
			"type": "string"
		},
		"category": {
			"type": "string"
		},
		"valueType": {
			"enum": [
				"boolean",
				"color",
				"currency",
				"fraction",
				"fractionAndPercentage",
				"number",
				"oneDecimalPlace",
				"percentage",
				"text",
				"view"
			],
			"type": "string"
		}
	}
}
