/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const MatrixReportSchema = {
	"additionalProperties": false,
	"type": "object",
	"properties": {
		"type": {
			"type": "string",
			"enum": [
				"matrix"
			]
		},
		"startDate": {
			"type": "string"
		},
		"endDate": {
			"type": "string"
		},
		"period": {
			"type": "object",
			"properties": {
				"earliestAvailable": {
					"type": "string"
				},
				"latestAvailable": {
					"type": "string"
				},
				"requested": {
					"type": "string"
				}
			},
			"additionalProperties": false
		},
		"columns": {
			"type": "array",
			"items": {
				"$ref": "#/definitions/MatrixReportColumn"
			}
		},
		"rows": {
			"type": "array",
			"items": {
				"additionalProperties": false,
				"type": "object",
				"properties": {
					"dataElement": {
						"anyOf": [
							{
								"type": "object",
								"properties": {
									"entityCode": {
										"type": "string"
									},
									"entityLabel": {
										"type": "string"
									}
								},
								"additionalProperties": false,
								"required": [
									"entityCode",
									"entityLabel"
								]
							},
							{
								"type": "string"
							}
						]
					},
					"categoryId": {
						"type": "string"
					},
					"category": {
						"type": "string"
					},
					"valueType": {
						"enum": [
							"boolean",
							"color",
							"currency",
							"fraction",
							"fractionAndPercentage",
							"number",
							"oneDecimalPlace",
							"percentage",
							"text",
							"view"
						],
						"type": "string"
					}
				}
			}
		}
	},
	"required": [
		"endDate",
		"startDate"
	]
}
