/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const MatrixEntityCellSchema = {
	"type": "object",
	"properties": {
		"entityCode": {
			"type": "string"
		},
		"entityLabel": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"entityCode",
		"entityLabel"
	]
}
