/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const MeasureTypeSchema = {
	"enum": [
		"color",
		"icon",
		"radius",
		"shaded-spectrum",
		"shading",
		"spectrum"
	],
	"type": "string"
}
