/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const MeasureColorSchemeSchema = {
	"enum": [
		"default",
		"default-reverse",
		"gpi",
		"performance"
	],
	"type": "string"
}
