/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const MeasureValueTypeSchema = {
	"enum": [
		"boolean",
		"currency",
		"default",
		"fraction",
		"fractionAndPercentage",
		"number",
		"numberAndPercentage",
		"oneDecimalPlace",
		"percentage",
		"text"
	],
	"type": "string"
}
