/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const MeditrakSyncQueueUpdateSchema = {
	"type": "object",
	"properties": {
		"change_time": {
			"type": "number"
		},
		"id": {
			"type": "string"
		},
		"record_id": {
			"type": "string"
		},
		"record_type": {
			"type": "string"
		},
		"type": {
			"type": "string"
		}
	},
	"additionalProperties": false
}
