/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const MeditrakSurveyResponseRequestSchema = {
	"type": "object",
	"additionalProperties": {},
	"properties": {
		"id": {
			"type": "string"
		},
		"survey_id": {
			"type": "string"
		},
		"user_id": {
			"type": "string"
		},
		"answers": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"id": {
						"type": "string"
					},
					"type": {
						"type": "string"
					},
					"body": {
						"anyOf": [
							{
								"type": "object",
								"additionalProperties": false
							},
							{
								"type": "string"
							}
						]
					},
					"question_id": {
						"type": "string"
					}
				},
				"additionalProperties": false,
				"required": [
					"body",
					"question_id",
					"type"
				]
			}
		},
		"clinic_id": {
			"type": "string"
		},
		"entity_id": {
			"type": "string"
		},
		"start_time": {
			"format": "iso-date-time",
			"type": "string"
		},
		"end_time": {
			"format": "iso-date-time",
			"type": "string"
		},
		"data_time": {
			"format": "iso-date-time",
			"type": "string"
		},
		"timestamp": {
			"format": "iso-date-time",
			"type": "string"
		},
		"approval_status": {
			"type": "string"
		},
		"entities_upserted": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"attributes": {
						"additionalProperties": false,
						"type": "object",
						"properties": {
							"type": {
								"type": "string"
							}
						}
					},
					"bounds": {
						"type": "string"
					},
					"code": {
						"type": "string"
					},
					"country_code": {
						"type": "string"
					},
					"id": {
						"type": "string"
					},
					"image_url": {
						"type": "string"
					},
					"metadata": {
						"type": "object",
						"properties": {
							"dhis": {
								"type": "object",
								"properties": {
									"dhisInstanceCode": {
										"type": "string"
									},
									"isDataRegional": {
										"type": "boolean"
									},
									"push": {
										"type": "boolean"
									},
									"trackedEntityId": {
										"type": "string"
									}
								},
								"additionalProperties": false
							},
							"ms1": {
								"type": "object",
								"properties": {
									"distributionId": {
										"type": "string"
									}
								},
								"additionalProperties": false
							},
							"openStreetMaps": {
								"type": "object",
								"properties": {
									"id": {
										"type": "string"
									}
								},
								"additionalProperties": false
							}
						},
						"additionalProperties": false
					},
					"name": {
						"type": "string"
					},
					"parent_id": {
						"type": "string"
					},
					"point": {
						"type": "string"
					},
					"region": {
						"type": "string"
					},
					"type": {
						"enum": [
							"asset",
							"bes_asset",
							"bes_office",
							"business",
							"case",
							"case_contact",
							"catchment",
							"city",
							"commune",
							"complaint",
							"consumable",
							"country",
							"disaster",
							"district",
							"district_operational",
							"document",
							"document_group",
							"enumeration_area",
							"facility",
							"facility_building",
							"facility_division",
							"facility_section",
							"farm",
							"fetp_graduate",
							"field_station",
							"fiji_aspen_facility",
							"health_clinic_boundary",
							"hospital_area",
							"hospital_ward",
							"household",
							"incident",
							"incident_reported",
							"individual",
							"institute",
							"ird_district",
							"ird_province",
							"ird_tehsil",
							"ird_village",
							"kiuar_area",
							"kiuar_facility",
							"larval_habitat",
							"larval_sample",
							"local_government",
							"maintenance",
							"medical_area",
							"msupply_store",
							"nursing_zone",
							"pacmossi_asset",
							"pacmossi_asset_facility",
							"pacmossi_asset_sub_facility",
							"pacmossi_consumable",
							"pacmossi_consumable_batch",
							"pacmossi_district",
							"pacmossi_insecticide_test",
							"pacmossi_spraying_site",
							"pacmossi_village",
							"pharmacy",
							"policy",
							"postcode",
							"project",
							"rehab_facility_model",
							"repair_request",
							"school",
							"spare_part",
							"srh_district",
							"srh_sub_district",
							"sub_catchment",
							"sub_district",
							"sub_facility",
							"supermarket",
							"tamanu_country",
							"tmf_district",
							"tmf_facility",
							"tmf_project",
							"tmf_sub_district",
							"transfer",
							"trap",
							"vehicle",
							"village",
							"visiting_specialist",
							"water_sample",
							"wholesaler",
							"wish_sub_district",
							"world"
						],
						"type": "string"
					},
					"updated_at_sync_tick": {
						"type": "string"
					}
				},
				"additionalProperties": false,
				"required": [
					"attributes",
					"code",
					"id",
					"metadata",
					"name",
					"type",
					"updated_at_sync_tick"
				]
			}
		},
		"options_created": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"label": {
						"type": "string"
					},
					"option_set_id": {
						"type": "string"
					},
					"value": {
						"type": "string"
					}
				},
				"additionalProperties": false,
				"required": [
					"option_set_id",
					"value"
				]
			}
		},
		"submission_time": {
			"description": "only used in meditrak-app-server, v1.7.87 to v1.9.110 (inclusive) uses submission_time",
			"type": "string"
		},
		"timezone": {
			"type": "string"
		}
	},
	"required": [
		"answers",
		"survey_id",
		"user_id"
	]
}
