/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const MeditrakDeviceCreateSchema = {
	"type": "object",
	"properties": {
		"app_version": {
			"type": "string"
		},
		"config": {
			"type": "object",
			"properties": {}
		},
		"install_id": {
			"type": "string"
		},
		"last_login": {
			"type": "string",
			"format": "date-time"
		},
		"platform": {
			"type": "string"
		},
		"user_id": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"install_id",
		"user_id"
	]
}
