/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const Ms1SyncLogSchema = {
	"type": "object",
	"properties": {
		"count": {
			"type": "number"
		},
		"data": {
			"type": "string"
		},
		"endpoint": {
			"type": "string"
		},
		"error_list": {
			"type": "string"
		},
		"id": {
			"type": "string"
		},
		"record_id": {
			"type": "string"
		},
		"record_type": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"id",
		"record_id",
		"record_type"
	]
}
