/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const MultiValueRowPresentationOptionsSchema = {
	"additionalProperties": false,
	"type": "object",
	"properties": {
		"color": {
			"description": "A CSS color string e.g. green or #abc123",
			"type": "string"
		},
		"header": {
			"type": "string"
		},
		"dataPairNames": {
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"rowHeader": {
			"additionalProperties": false,
			"type": "object",
			"properties": {
				"color": {
					"description": "A CSS color string e.g. green or #abc123",
					"type": "string"
				},
				"name": {
					"type": "string"
				}
			},
			"required": [
				"color"
			]
		},
		"leftColumn": {
			"additionalProperties": false,
			"type": "object",
			"properties": {
				"color": {
					"description": "A CSS color string e.g. green or #abc123",
					"type": "string"
				},
				"header": {
					"type": "string"
				}
			},
			"required": [
				"color",
				"header"
			]
		},
		"rightColumn": {
			"additionalProperties": false,
			"type": "object",
			"properties": {
				"color": {
					"description": "A CSS color string e.g. green or #abc123",
					"type": "string"
				},
				"header": {
					"type": "string"
				}
			},
			"required": [
				"color",
				"header"
			]
		},
		"middleColumn": {
			"additionalProperties": false,
			"type": "object",
			"properties": {
				"color": {
					"description": "A CSS color string e.g. green or #abc123",
					"type": "string"
				},
				"header": {
					"type": "string"
				}
			},
			"required": [
				"color",
				"header"
			]
		}
	},
	"required": [
		"color",
		"header"
	]
}
