/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const MultiValuePresentationOptionsSchema = {
	"additionalProperties": false,
	"type": "object",
	"properties": {
		"isTitleVisible": {
			"type": "boolean"
		},
		"valueFormat": {
			"description": "This can be anything from the [numeraljs library]{@link http://numeraljs.com/#format}",
			"type": "string"
		}
	}
}
