/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const MultiValueViewConfigSchema = {
	"additionalProperties": false,
	"type": "object",
	"properties": {
		"name": {
			"description": "The title of the viz",
			"type": "string"
		},
		"description": {
			"description": "A short description that appears above a viz",
			"type": "string"
		},
		"periodGranularity": {
			"description": "Granularity of dates in the viz. Controls the date picker and x axis granularity",
			"enum": [
				"day",
				"month",
				"one_day_at_a_time",
				"one_month_at_a_time",
				"one_quarter_at_a_time",
				"one_week_at_a_time",
				"one_year_at_a_time",
				"quarter",
				"week",
				"year"
			],
			"type": "string"
		},
		"dateOffset": {
			"description": "The number of periods to offset the date range by, for single date period granularities. E.g. if the period granularity is 'one_year_at_a_time' and the date offset is 6 months, the year will run from July-June. Only months and quarter offsets are supported.\nCurrently only works for 'one_year_at_a_time' and 'year' granularities -  assume that any other granularities used with this will not work as expected.",
			"type": "object",
			"properties": {
				"unit": {
					"enum": [
						"month",
						"quarter"
					],
					"type": "string"
				},
				"offset": {
					"type": "number"
				}
			},
			"additionalProperties": false,
			"required": [
				"offset",
				"unit"
			]
		},
		"defaultTimePeriod": {
			"description": "Initial date range for this viz.\nEither a single offset, or an ISO string / offset for start/end date\neg.\n// Single offset\n\"defaultTimePeriod\": {\n  \"unit\": \"week\",\n  \"offset\": 7\n}\n\n// Explicit start/end dates\n\"defaultTimePeriod\": {\n  \"start\": \"2022-10-01\",\n  \"end\": \"2023-06-30\"\n}\n\n// Start/end date offsets\n\"defaultTimePeriod\": {\n  \"start\": {\n    \"unit\": \"week\",\n    \"offset\": -52\n  },\n  \"end\": {\n    \"unit\": \"week\",\n    \"offset\": 3\n  }\n}",
			"anyOf": [
				{
					"type": "object",
					"properties": {
						"unit": {
							"description": "Time unit to offset by",
							"enum": [
								"day",
								"month",
								"quarter",
								"week",
								"year"
							],
							"type": "string"
						},
						"offset": {
							"description": "Offset distance (can be negative to offset to an earlier date)",
							"type": "number"
						},
						"modifier": {
							"description": "Used to modify the offset by either moving the date to the start/end of the modifier unit",
							"enum": [
								"end_of",
								"start_of"
							],
							"type": "string"
						},
						"modifierUnit": {
							"description": "Time unit to modify the offset by",
							"enum": [
								"day",
								"month",
								"quarter",
								"week",
								"year"
							],
							"type": "string"
						}
					},
					"additionalProperties": false,
					"required": [
						"unit"
					]
				},
				{
					"type": "object",
					"properties": {
						"start": {
							"description": "Either an ISO Date string, or an offset object",
							"anyOf": [
								{
									"type": "object",
									"properties": {
										"unit": {
											"description": "Time unit to offset by",
											"enum": [
												"day",
												"month",
												"quarter",
												"week",
												"year"
											],
											"type": "string"
										},
										"offset": {
											"description": "Offset distance (can be negative to offset to an earlier date)",
											"type": "number"
										},
										"modifier": {
											"description": "Used to modify the offset by either moving the date to the start/end of the modifier unit",
											"enum": [
												"end_of",
												"start_of"
											],
											"type": "string"
										},
										"modifierUnit": {
											"description": "Time unit to modify the offset by",
											"enum": [
												"day",
												"month",
												"quarter",
												"week",
												"year"
											],
											"type": "string"
										}
									},
									"additionalProperties": false,
									"required": [
										"unit"
									]
								},
								{
									"type": "string"
								}
							]
						},
						"end": {
							"description": "Either an ISO Date string, or an offset object",
							"anyOf": [
								{
									"type": "object",
									"properties": {
										"unit": {
											"description": "Time unit to offset by",
											"enum": [
												"day",
												"month",
												"quarter",
												"week",
												"year"
											],
											"type": "string"
										},
										"offset": {
											"description": "Offset distance (can be negative to offset to an earlier date)",
											"type": "number"
										},
										"modifier": {
											"description": "Used to modify the offset by either moving the date to the start/end of the modifier unit",
											"enum": [
												"end_of",
												"start_of"
											],
											"type": "string"
										},
										"modifierUnit": {
											"description": "Time unit to modify the offset by",
											"enum": [
												"day",
												"month",
												"quarter",
												"week",
												"year"
											],
											"type": "string"
										}
									},
									"additionalProperties": false,
									"required": [
										"unit"
									]
								},
								{
									"type": "string"
								}
							]
						}
					},
					"additionalProperties": false
				}
			]
		},
		"datePickerLimits": {
			"description": "Maximum date ranges that the date picker can be used to choose from",
			"type": "object",
			"properties": {
				"start": {
					"type": "object",
					"properties": {
						"unit": {
							"description": "Time unit to offset by",
							"enum": [
								"day",
								"month",
								"quarter",
								"week",
								"year"
							],
							"type": "string"
						},
						"offset": {
							"description": "Offset distance (can be negative to offset to an earlier date)",
							"type": "number"
						},
						"modifier": {
							"description": "Used to modify the offset by either moving the date to the start/end of the modifier unit",
							"enum": [
								"end_of",
								"start_of"
							],
							"type": "string"
						},
						"modifierUnit": {
							"description": "Time unit to modify the offset by",
							"enum": [
								"day",
								"month",
								"quarter",
								"week",
								"year"
							],
							"type": "string"
						}
					},
					"additionalProperties": false,
					"required": [
						"unit"
					]
				},
				"end": {
					"type": "object",
					"properties": {
						"unit": {
							"description": "Time unit to offset by",
							"enum": [
								"day",
								"month",
								"quarter",
								"week",
								"year"
							],
							"type": "string"
						},
						"offset": {
							"description": "Offset distance (can be negative to offset to an earlier date)",
							"type": "number"
						},
						"modifier": {
							"description": "Used to modify the offset by either moving the date to the start/end of the modifier unit",
							"enum": [
								"end_of",
								"start_of"
							],
							"type": "string"
						},
						"modifierUnit": {
							"description": "Time unit to modify the offset by",
							"enum": [
								"day",
								"month",
								"quarter",
								"week",
								"year"
							],
							"type": "string"
						}
					},
					"additionalProperties": false,
					"required": [
						"unit"
					]
				}
			},
			"additionalProperties": false
		},
		"exportConfig": {
			"description": "Extra config options for exporting",
			"type": "object",
			"properties": {
				"dataElementHeader": {
					"description": "Sets the header for the data element in xls exports",
					"type": "string"
				}
			},
			"additionalProperties": false
		},
		"noDataMessage": {
			"description": "Message which shows if no data is found",
			"type": "string"
		},
		"noDataFetch": {
			"description": "If true, Tupaia will not fetch any data for this viz. Usually used with custom vizes of type: component, e.g. ProjectDescription.",
			"default": false,
			"type": "boolean"
		},
		"drillDown": {
			"description": "Configure drill down functionality in this viz to allow clicking through to another visual",
			"type": "object",
			"properties": {
				"itemCode": {
					"description": "The code of the dashboard item that drilling down through this viz should take you to",
					"type": "string"
				},
				"keyLink": {
					"type": "string"
				},
				"parameterLink": {
					"description": "Parameter that the value which is drilled through should link to when fetching data for the drill down dashboard item",
					"type": "string"
				},
				"itemCodeByEntry": {
					"description": "A map of series codes to dashboard item codes that drilling down each series should take you to",
					"type": "object",
					"additionalProperties": {
						"type": "string"
					}
				}
			},
			"additionalProperties": false
		},
		"entityHeader": {
			"description": "",
			"type": "string"
		},
		"reference": {
			"description": "If provided shows an (i) icon next to the viz title, which allows linking to the source data",
			"anyOf": [
				{
					"description": "One of the two shapes which {@link ReferenceProps} can take.",
					"type": "object",
					"properties": {
						"text": {
							"type": "string"
						}
					},
					"additionalProperties": false,
					"required": [
						"text"
					]
				},
				{
					"description": "One of the two shapes which {@link ReferenceProps} can take.",
					"type": "object",
					"properties": {
						"name": {
							"type": "string"
						},
						"link": {
							"type": "string"
						}
					},
					"additionalProperties": false,
					"required": [
						"link",
						"name"
					]
				}
			]
		},
		"source": {
			"description": "If specified allows the frontend to know where the data is coming from, so if there is no data it can show a custom no-data message e.g. \"Requires mSupply\".",
			"type": "string"
		},
		"weekDisplayFormat": {
			"description": "Allows customising how weeks are displayed, e.g. 'W/C 6 Jan 2020' or 'ISO Week 2 2020'",
			"default": "'WEEK_COMMENCING_ABBR'",
			"enum": [
				"ISO_WEEK_NUMBER",
				"WEEK_COMMENCING",
				"WEEK_COMMENCING_ABBR",
				"WEEK_ENDING",
				"WEEK_ENDING_ABBR"
			],
			"type": "string"
		},
		"dateRangeDelimiter": {
			"description": "If specified, this delimiter will be used to separate the start and end dates in the date range picker. Defaults to '-'. This only applies to dates when the type is a single date but has an offset. E.g. offset of 6 months with a date range delimiter of '/' will show 'Jul 2022/June 2023'",
			"type": "string"
		},
		"type": {
			"type": "string",
			"enum": [
				"view"
			]
		},
		"viewType": {
			"type": "string",
			"enum": [
				"multiValue"
			]
		},
		"valueType": {
			"enum": [
				"boolean",
				"color",
				"currency",
				"fraction",
				"fractionAndPercentage",
				"number",
				"oneDecimalPlace",
				"percentage",
				"text",
				"view"
			],
			"type": "string"
		},
		"value_metadata": {
			"type": "object",
			"additionalProperties": false
		},
		"presentationOptions": {
			"additionalProperties": false,
			"type": "object",
			"properties": {
				"isTitleVisible": {
					"type": "boolean"
				},
				"valueFormat": {
					"description": "This can be anything from the [numeraljs library]{@link http://numeraljs.com/#format}",
					"type": "string"
				}
			}
		}
	},
	"required": [
		"name",
		"type",
		"viewType"
	]
}
