/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const OneTimeLoginSchema = {
	"type": "object",
	"properties": {
		"creation_date": {
			"type": "string",
			"format": "date-time"
		},
		"id": {
			"type": "string"
		},
		"token": {
			"type": "string"
		},
		"use_date": {
			"type": "string",
			"format": "date-time"
		},
		"user_id": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"id",
		"token",
		"user_id"
	]
}
