/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const OptionSetUpdateSchema = {
	"type": "object",
	"properties": {
		"id": {
			"type": "string"
		},
		"name": {
			"type": "string"
		}
	},
	"additionalProperties": false
}
