/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const OptionSchema = {
	"type": "object",
	"properties": {
		"attributes": {
			"type": "object",
			"properties": {
				"parent_category": {
					"type": "string"
				},
				"grandparent_category": {
					"type": "string"
				}
			},
			"additionalProperties": false
		},
		"id": {
			"type": "string"
		},
		"label": {
			"type": "string"
		},
		"option_set_id": {
			"type": "string"
		},
		"sort_order": {
			"type": "number"
		},
		"updated_at_sync_tick": {
			"type": "string"
		},
		"value": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"id",
		"option_set_id",
		"sort_order",
		"updated_at_sync_tick",
		"value"
	]
}
