/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const OptionAttributesSchema = {
	"type": "object",
	"properties": {
		"parent_category": {
			"type": "string"
		},
		"grandparent_category": {
			"type": "string"
		}
	},
	"additionalProperties": false
}
