/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const OptionUpdateSchema = {
	"type": "object",
	"properties": {
		"attributes": {
			"type": "object",
			"properties": {
				"parent_category": {
					"type": "string"
				},
				"grandparent_category": {
					"type": "string"
				}
			},
			"additionalProperties": false
		},
		"id": {
			"type": "string"
		},
		"label": {
			"type": "string"
		},
		"option_set_id": {
			"type": "string"
		},
		"sort_order": {
			"type": "number"
		},
		"value": {
			"type": "string"
		}
	},
	"additionalProperties": false
}
