/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const PeriodUnitSchema = {
	"enum": [
		"day",
		"month",
		"quarter",
		"week",
		"year"
	],
	"type": "string"
}
