/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const PeriodGranularitySchema = {
	"enum": [
		"daily",
		"monthly",
		"quarterly",
		"weekly",
		"yearly"
	],
	"type": "string"
}
