/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const PieChartSegmentConfigSchema = {
	"type": "object",
	"additionalProperties": {
		"type": "object",
		"properties": {
			"color": {
				"description": "A CSS color string e.g. green or #abc123",
				"type": "string"
			},
			"label": {
				"type": "string"
			}
		},
		"additionalProperties": false
	}
}
