/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const PlaintextReferencePropsSchema = {
	"description": "One of the two shapes which {@link ReferenceProps} can take.",
	"type": "object",
	"properties": {
		"text": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"text"
	]
}
