/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const PresentationOptionConditionSchema = {
	"additionalProperties": false,
	"type": "object",
	"properties": {
		"color": {
			"description": "Specify the color of the display item",
			"type": "string"
		},
		"description": {
			"description": "Specify the text for the legend item. Also used in the enlarged cell view",
			"type": "string"
		},
		"label": {
			"description": "Specify if you want a label to appear above the enlarged",
			"type": "string"
		},
		"key": {
			"type": "string"
		},
		"condition": {
			"description": "the value to match against exactly, or an object with match criteria e.g. { '>=': 5.5 }",
			"anyOf": [
				{
					"type": "object",
					"properties": {
						"=": {
							"type": [
								"string",
								"number"
							]
						},
						">": {
							"type": [
								"string",
								"number"
							]
						},
						"<": {
							"type": [
								"string",
								"number"
							]
						},
						">=": {
							"type": [
								"string",
								"number"
							]
						},
						"<=": {
							"type": [
								"string",
								"number"
							]
						}
					},
					"additionalProperties": false
				},
				{
					"type": [
						"string",
						"number"
					]
				}
			]
		},
		"legendLabel": {
			"type": "string"
		}
	},
	"required": [
		"condition",
		"key"
	]
}
