/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const PresentationOptionRangeSchema = {
	"additionalProperties": false,
	"type": "object",
	"properties": {
		"color": {
			"description": "Specify the color of the display item",
			"type": "string"
		},
		"description": {
			"description": "Specify the text for the legend item. Also used in the enlarged cell view",
			"type": "string"
		},
		"label": {
			"description": "Specify if you want a label to appear above the enlarged",
			"type": "string"
		},
		"min": {
			"type": "number"
		},
		"max": {
			"type": "number"
		}
	}
}
