/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const PresentationOptionsSchema = {
	"anyOf": [
		{
			"type": "object",
			"properties": {
				"type": {
					"type": "string",
					"enum": [
						"condition"
					]
				},
				"conditions": {
					"type": "array",
					"items": {
						"additionalProperties": false,
						"type": "object",
						"properties": {
							"color": {
								"description": "Specify the color of the display item",
								"type": "string"
							},
							"description": {
								"description": "Specify the text for the legend item. Also used in the enlarged cell view",
								"type": "string"
							},
							"label": {
								"description": "Specify if you want a label to appear above the enlarged",
								"type": "string"
							},
							"key": {
								"type": "string"
							},
							"condition": {
								"description": "the value to match against exactly, or an object with match criteria e.g. { '>=': 5.5 }",
								"anyOf": [
									{
										"type": "object",
										"properties": {
											"=": {
												"type": [
													"string",
													"number"
												]
											},
											">": {
												"type": [
													"string",
													"number"
												]
											},
											"<": {
												"type": [
													"string",
													"number"
												]
											},
											">=": {
												"type": [
													"string",
													"number"
												]
											},
											"<=": {
												"type": [
													"string",
													"number"
												]
											}
										},
										"additionalProperties": false
									},
									{
										"type": [
											"string",
											"number"
										]
									}
								]
							},
							"legendLabel": {
								"type": "string"
							}
						},
						"required": [
							"condition",
							"key"
						]
					}
				},
				"showRawValue": {
					"default": false,
					"type": "boolean"
				},
				"showNestedRows": {
					"default": false,
					"type": "boolean"
				},
				"applyLocation": {
					"description": "Specify if you want to limit where to apply the conditional presentation",
					"type": "object",
					"properties": {
						"columnIndexes": {
							"type": "array",
							"items": {
								"type": "number"
							}
						}
					},
					"additionalProperties": false,
					"required": [
						"columnIndexes"
					]
				}
			},
			"additionalProperties": false
		},
		{
			"additionalProperties": false,
			"type": "object",
			"properties": {
				"type": {
					"type": "string",
					"enum": [
						"range"
					]
				},
				"showRawValue": {
					"type": "boolean"
				}
			},
			"required": [
				"type"
			]
		},
		{
			"additionalProperties": false,
			"type": "object",
			"properties": {
				"exportWithLabels": {
					"description": "Include labels for each point of data in exports",
					"type": "boolean"
				},
				"exportWithTable": {
					"description": "Include the data table below the viz in exports",
					"type": "boolean"
				},
				"exportWithTableDisabled": {
					"description": "Set to 'true' to prevent users from exporting this viz with the data table",
					"type": "boolean"
				},
				"periodTickFormat": {
					"description": "This string is one of the [Moment.js format]{@link https://momentjs.com/docs/#/displaying/format/} values",
					"type": "string"
				},
				"hideAverage": {
					"description": "Hides the data average line",
					"type": "boolean"
				},
				"referenceLines": {
					"description": "Configure reference lines to appear in on the viz",
					"type": "object",
					"properties": {
						"targetLine": {
							"type": "object",
							"properties": {
								"referenceValue": {
									"description": "Value where the reference line is drawn (if not given no reference line will be drawn)",
									"type": "number"
								},
								"referenceLabel": {
									"description": "Label shown on the reference line",
									"type": "string"
								}
							},
							"additionalProperties": false,
							"required": [
								"referenceValue"
							]
						}
					},
					"additionalProperties": false
				}
			}
		},
		{
			"additionalProperties": false,
			"type": "object",
			"properties": {
				"exportWithLabels": {
					"description": "Include labels for each point of data in exports",
					"type": "boolean"
				},
				"exportWithTable": {
					"description": "Include the data table below the viz in exports",
					"type": "boolean"
				},
				"exportWithTableDisabled": {
					"description": "Set to 'true' to prevent users from exporting this viz with the data table",
					"type": "boolean"
				}
			}
		},
		{
			"additionalProperties": false,
			"type": "object",
			"properties": {
				"exportWithLabels": {
					"description": "Include labels for each point of data in exports",
					"type": "boolean"
				},
				"exportWithTable": {
					"description": "Include the data table below the viz in exports",
					"type": "boolean"
				},
				"exportWithTableDisabled": {
					"description": "Set to 'true' to prevent users from exporting this viz with the data table",
					"type": "boolean"
				},
				"periodTickFormat": {
					"description": "This string is one of the [Moment.js format]{@link https://momentjs.com/docs/#/displaying/format/} values",
					"type": "string"
				},
				"hideAverage": {
					"description": "Hides the data average line",
					"type": "boolean"
				},
				"referenceLines": {
					"description": "Configure reference lines to appear in on the viz",
					"type": "object",
					"properties": {
						"targetLine": {
							"type": "object",
							"properties": {
								"referenceValue": {
									"description": "Value where the reference line is drawn (if not given no reference line will be drawn)",
									"type": "number"
								},
								"referenceLabel": {
									"description": "Label shown on the reference line",
									"type": "string"
								}
							},
							"additionalProperties": false,
							"required": [
								"referenceValue"
							]
						}
					},
					"additionalProperties": false
				},
				"color": {
					"description": "A CSS color string e.g. green or #abc123",
					"type": "string"
				},
				"valueFormat": {
					"description": "This can be anything from the [numeraljs library]{@link http://numeraljs.com/#format}",
					"type": "string"
				}
			}
		},
		{
			"additionalProperties": false,
			"type": "object",
			"properties": {
				"isTitleVisible": {
					"type": "boolean"
				},
				"valueFormat": {
					"description": "This can be anything from the [numeraljs library]{@link http://numeraljs.com/#format}",
					"type": "string"
				}
			}
		},
		{
			"additionalProperties": false,
			"type": "object",
			"properties": {
				"color": {
					"description": "A CSS color string e.g. green or #abc123",
					"type": "string"
				},
				"header": {
					"type": "string"
				},
				"dataPairNames": {
					"type": "array",
					"items": {
						"type": "string"
					}
				},
				"rowHeader": {
					"additionalProperties": false,
					"type": "object",
					"properties": {
						"color": {
							"description": "A CSS color string e.g. green or #abc123",
							"type": "string"
						},
						"name": {
							"type": "string"
						}
					},
					"required": [
						"color"
					]
				},
				"leftColumn": {
					"additionalProperties": false,
					"type": "object",
					"properties": {
						"color": {
							"description": "A CSS color string e.g. green or #abc123",
							"type": "string"
						},
						"header": {
							"type": "string"
						}
					},
					"required": [
						"color",
						"header"
					]
				},
				"rightColumn": {
					"additionalProperties": false,
					"type": "object",
					"properties": {
						"color": {
							"description": "A CSS color string e.g. green or #abc123",
							"type": "string"
						},
						"header": {
							"type": "string"
						}
					},
					"required": [
						"color",
						"header"
					]
				},
				"middleColumn": {
					"additionalProperties": false,
					"type": "object",
					"properties": {
						"color": {
							"description": "A CSS color string e.g. green or #abc123",
							"type": "string"
						},
						"header": {
							"type": "string"
						}
					},
					"required": [
						"color",
						"header"
					]
				}
			},
			"required": [
				"color",
				"header"
			]
		}
	]
}
