/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const ProjectSchema = {
	"type": "object",
	"properties": {
		"code": {
			"type": "string"
		},
		"config": {
			"type": "object",
			"properties": {
				"frontendExcluded": {
					"type": "array",
					"items": {
						"type": "object",
						"properties": {
							"types": {
								"type": "array",
								"items": {
									"type": "string"
								}
							},
							"exceptions": {
								"type": "object",
								"properties": {
									"permissionGroups": {
										"type": "array",
										"items": {
											"type": "string"
										}
									}
								},
								"additionalProperties": false,
								"required": [
									"permissionGroups"
								]
							}
						},
						"additionalProperties": false,
						"required": [
							"types"
						]
					}
				},
				"permanentRegionLabels": {
					"type": "boolean"
				},
				"tileSets": {
					"type": "string"
				},
				"includeDefaultTileSets": {
					"type": "boolean"
				},
				"projectDashboardHeader": {
					"type": "string"
				},
				"hideCoconutsAndPigs": {
					"type": "boolean"
				}
			},
			"additionalProperties": false
		},
		"dashboard_group_name": {
			"type": "string"
		},
		"default_measure": {
			"type": "string"
		},
		"description": {
			"type": "string"
		},
		"entity_hierarchy_id": {
			"type": "string"
		},
		"entity_id": {
			"type": "string"
		},
		"id": {
			"type": "string"
		},
		"image_url": {
			"type": "string"
		},
		"logo_url": {
			"type": "string"
		},
		"permission_groups": {
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"sort_order": {
			"type": "number"
		},
		"updated_at_sync_tick": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"code",
		"config",
		"id",
		"permission_groups",
		"updated_at_sync_tick"
	]
}
