/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const ProjectResponseSchema = {
	"additionalProperties": false,
	"type": "object",
	"properties": {
		"code": {
			"type": "string"
		},
		"config": {
			"type": "object",
			"properties": {
				"frontendExcluded": {
					"type": "array",
					"items": {
						"type": "object",
						"properties": {
							"types": {
								"type": "array",
								"items": {
									"type": "string"
								}
							},
							"exceptions": {
								"type": "object",
								"properties": {
									"permissionGroups": {
										"type": "array",
										"items": {
											"type": "string"
										}
									}
								},
								"additionalProperties": false,
								"required": [
									"permissionGroups"
								]
							}
						},
						"additionalProperties": false,
						"required": [
							"types"
						]
					}
				},
				"permanentRegionLabels": {
					"type": "boolean"
				},
				"tileSets": {
					"type": "string"
				},
				"includeDefaultTileSets": {
					"type": "boolean"
				},
				"projectDashboardHeader": {
					"type": "string"
				},
				"hideCoconutsAndPigs": {
					"type": "boolean"
				}
			},
			"additionalProperties": false
		},
		"dashboardGroupName": {
			"type": "string"
		},
		"defaultMeasure": {
			"type": "string"
		},
		"description": {
			"type": "string"
		},
		"entityHierarchyId": {
			"type": "string"
		},
		"entityId": {
			"type": "string"
		},
		"id": {
			"type": "string"
		},
		"imageUrl": {
			"type": "string"
		},
		"logoUrl": {
			"type": "string"
		},
		"permissionGroups": {
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"sortOrder": {
			"type": "number"
		},
		"updatedAtSyncTick": {
			"type": "string"
		},
		"hasAccess": {
			"type": "boolean"
		},
		"hasPendingAccess": {
			"type": "boolean"
		},
		"homeEntityCode": {
			"type": "string"
		},
		"name": {
			"type": "string"
		},
		"names": {
			"type": "array",
			"items": {
				"type": "string"
			}
		}
	},
	"required": [
		"code",
		"config",
		"hasAccess",
		"hasPendingAccess",
		"homeEntityCode",
		"id",
		"name",
		"permissionGroups",
		"updatedAtSyncTick"
	]
}
