/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const ProjectConfigSchema = {
	"type": "object",
	"properties": {
		"frontendExcluded": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"types": {
						"type": "array",
						"items": {
							"type": "string"
						}
					},
					"exceptions": {
						"type": "object",
						"properties": {
							"permissionGroups": {
								"type": "array",
								"items": {
									"type": "string"
								}
							}
						},
						"additionalProperties": false,
						"required": [
							"permissionGroups"
						]
					}
				},
				"additionalProperties": false,
				"required": [
					"types"
				]
			}
		},
		"permanentRegionLabels": {
			"type": "boolean"
		},
		"tileSets": {
			"type": "string"
		},
		"includeDefaultTileSets": {
			"type": "boolean"
		},
		"projectDashboardHeader": {
			"type": "string"
		},
		"hideCoconutsAndPigs": {
			"type": "boolean"
		}
	},
	"additionalProperties": false
}
