/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const QuerySchema = {
	"type": "object",
	"properties": {
		"email": {
			"type": "string"
		},
		"token": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"email",
		"token"
	]
}
