/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const QuestionSchema = {
	"type": "object",
	"properties": {
		"code": {
			"type": "string"
		},
		"data_element_id": {
			"type": "string"
		},
		"detail": {
			"type": "string"
		},
		"hook": {
			"type": "string"
		},
		"id": {
			"type": "string"
		},
		"name": {
			"type": "string"
		},
		"option_set_id": {
			"type": "string"
		},
		"options": {
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"text": {
			"type": "string"
		},
		"type": {
			"enum": [
				"Arithmetic",
				"Autocomplete",
				"Binary",
				"Checkbox",
				"CodeGenerator",
				"Condition",
				"Date",
				"DateOfData",
				"DateTime",
				"Entity",
				"File",
				"FreeText",
				"Geolocate",
				"Instruction",
				"Number",
				"Photo",
				"PrimaryEntity",
				"Radio",
				"SubmissionDate",
				"Task",
				"User"
			],
			"type": "string"
		},
		"updated_at_sync_tick": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"id",
		"text",
		"type",
		"updated_at_sync_tick"
	]
}
