/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const QuestionTypeSchema = {
	"enum": [
		"Arithmetic",
		"Autocomplete",
		"Binary",
		"Checkbox",
		"CodeGenerator",
		"Condition",
		"Date",
		"DateOfData",
		"DateTime",
		"Entity",
		"File",
		"FreeText",
		"Geolocate",
		"Instruction",
		"Number",
		"Photo",
		"PrimaryEntity",
		"Radio",
		"SubmissionDate",
		"Task",
		"User"
	],
	"type": "string"
}
