/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const QueueStatusSchema = {
	"enum": [
		"activeSync",
		"waitingInQueue"
	],
	"type": "string"
}
