/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const RangePresentationOptionsSchema = {
	"additionalProperties": false,
	"type": "object",
	"properties": {
		"type": {
			"type": "string",
			"enum": [
				"range"
			]
		},
		"showRawValue": {
			"type": "boolean"
		}
	},
	"required": [
		"type"
	]
}
