/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const RecentSurveySchema = {
	"type": "object",
	"properties": {
		"countryCode": {
			"type": "string"
		},
		"countryId": {
			"type": "string"
		},
		"countryName": {
			"type": "string"
		},
		"surveyCode": {
			"type": "string"
		},
		"surveyName": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"countryCode",
		"countryId",
		"countryName",
		"surveyCode",
		"surveyName"
	]
}
