/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const ReferenceLinesConfigSchema = {
	"type": "object",
	"properties": {
		"referenceValue": {
			"description": "Value where the reference line is drawn (if not given no reference line will be drawn)",
			"type": "number"
		},
		"referenceLabel": {
			"description": "Label shown on the reference line",
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"referenceValue"
	]
}
