/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const ReferencePropsSchema = {
	"description": "Props for the reference prop of the `ReferenceTooltip` ui-component. It can have either a piece\nof plaintext to display in the tooltip, or a named link; but not both.",
	"anyOf": [
		{
			"description": "One of the two shapes which {@link ReferenceProps} can take.",
			"type": "object",
			"properties": {
				"text": {
					"type": "string"
				}
			},
			"additionalProperties": false,
			"required": [
				"text"
			]
		},
		{
			"description": "One of the two shapes which {@link ReferenceProps} can take.",
			"type": "object",
			"properties": {
				"name": {
					"type": "string"
				},
				"link": {
					"type": "string"
				}
			},
			"additionalProperties": false,
			"required": [
				"link",
				"name"
			]
		}
	]
}
