/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const RefreshTokenSchema = {
	"type": "object",
	"properties": {
		"device": {
			"type": "string"
		},
		"expiry": {
			"type": "number"
		},
		"id": {
			"type": "string"
		},
		"meditrak_device_id": {
			"type": "string"
		},
		"token": {
			"type": "string"
		},
		"user_id": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"id",
		"token",
		"user_id"
	]
}
