/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const RepeatScheduleSchema = {
	"additionalProperties": false,
	"type": "object",
	"properties": {
		"freq": {
			"type": "number"
		},
		"interval": {
			"type": "number"
		},
		"bymonthday": {
			"anyOf": [
				{
					"type": "array",
					"items": {
						"type": "number"
					}
				},
				{
					"type": "number"
				}
			]
		},
		"bysetpos": {
			"anyOf": [
				{
					"type": "array",
					"items": {
						"type": "number"
					}
				},
				{
					"type": "number"
				}
			]
		},
		"dtstart": {
			"type": "string",
			"format": "date-time"
		}
	}
}
