/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const ReportCreateSchema = {
	"type": "object",
	"properties": {
		"code": {
			"type": "string"
		},
		"config": {
			"anyOf": [
				{
					"type": "object",
					"properties": {
						"transform": {
							"type": "array",
							"items": {
								"anyOf": [
									{
										"type": "object",
										"additionalProperties": false
									},
									{
										"type": "string"
									}
								]
							}
						},
						"output": {
							"additionalProperties": false,
							"type": "object",
							"properties": {
								"type": {
									"type": "string"
								}
							}
						}
					},
					"additionalProperties": false,
					"required": [
						"transform"
					]
				},
				{
					"type": "object",
					"properties": {
						"customReport": {
							"type": "string"
						}
					},
					"additionalProperties": false,
					"required": [
						"customReport"
					]
				}
			]
		},
		"latest_data_parameters": {
			"type": "object",
			"properties": {}
		},
		"permission_group_id": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"code",
		"config",
		"permission_group_id"
	]
}
