/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const ReqBodySchema = {
	"type": "object",
	"properties": {
		"inputMessage": {
			"type": "string"
		},
		"dataStructure": {
			"type": "object",
			"additionalProperties": false
		},
		"presentationOptions": {
			"type": "object",
			"additionalProperties": false
		}
	},
	"additionalProperties": false,
	"required": [
		"dataStructure",
		"inputMessage",
		"presentationOptions"
	]
}
