/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const ReqQuerySchema = {
	"type": "object",
	"properties": {
		"fields": {
			"type": "array",
			"items": {
				"type": "string"
			}
		}
	},
	"additionalProperties": false
}
