/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const ScaleTypeSchema = {
	"enum": [
		"gpi",
		"neutral",
		"neutralReverse",
		"performance",
		"performanceDesc"
	],
	"type": "string"
}
