/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const SettingUpdateSchema = {
	"type": "object",
	"properties": {
		"id": {
			"type": "string"
		},
		"key": {
			"type": "string"
		},
		"value": {
			"type": "string"
		}
	},
	"additionalProperties": false
}
