/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const SettingCreateSchema = {
	"type": "object",
	"properties": {
		"key": {
			"type": "string"
		},
		"value": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"key"
	]
}
