/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const StandardReportConfigSchema = {
	"type": "object",
	"properties": {
		"transform": {
			"type": "array",
			"items": {
				"anyOf": [
					{
						"type": "object",
						"additionalProperties": false
					},
					{
						"type": "string"
					}
				]
			}
		},
		"output": {
			"additionalProperties": false,
			"type": "object",
			"properties": {
				"type": {
					"type": "string"
				}
			}
		}
	},
	"additionalProperties": false,
	"required": [
		"transform"
	]
}
