/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const SubscribeDashboardRequestSchema = {
	"type": "object",
	"properties": {
		"email": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"email"
	]
}
