/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const SupersetInstanceCreateSchema = {
	"type": "object",
	"properties": {
		"code": {
			"type": "string"
		},
		"config": {
			"type": "object",
			"properties": {
				"serverName": {
					"type": "string"
				},
				"baseUrl": {
					"type": "string"
				},
				"insecure": {
					"type": "boolean"
				}
			},
			"additionalProperties": false,
			"required": [
				"baseUrl"
			]
		}
	},
	"additionalProperties": false,
	"required": [
		"code",
		"config"
	]
}
