/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const SurveyResponseTemplateVariablesSchema = {
	"type": "object",
	"properties": {
		"surveyName": {
			"type": "string"
		},
		"countryName": {
			"type": "string"
		},
		"regionName": {
			"type": "string"
		},
		"imageUrl": {
			"type": "string"
		},
		"link": {
			"type": "string"
		},
		"authorName": {
			"type": "string"
		}
	},
	"additionalProperties": false
}
