/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const SurveyResponseUpdateSchema = {
	"type": "object",
	"properties": {
		"approval_status": {
			"enum": [
				"approved",
				"not_required",
				"pending",
				"rejected"
			],
			"type": "string"
		},
		"assessor_name": {
			"type": "string"
		},
		"data_time": {
			"type": "string",
			"format": "date-time"
		},
		"end_time": {
			"type": "string",
			"format": "date-time"
		},
		"entity_id": {
			"type": "string"
		},
		"id": {
			"type": "string"
		},
		"metadata": {
			"type": "string"
		},
		"outdated": {
			"type": "boolean"
		},
		"start_time": {
			"type": "string",
			"format": "date-time"
		},
		"survey_id": {
			"type": "string"
		},
		"timezone": {
			"type": "string"
		},
		"user_id": {
			"type": "string"
		}
	},
	"additionalProperties": false
}
