/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const SurveyResponseDraftCreateSchema = {
	"type": "object",
	"properties": {
		"country_code": {
			"type": "string"
		},
		"entity_id": {
			"type": "string"
		},
		"form_data": {
			"type": "object",
			"properties": {}
		},
		"is_deleted": {
			"type": "boolean"
		},
		"screen_number": {
			"type": "number"
		},
		"start_time": {
			"type": "string",
			"format": "date-time"
		},
		"survey_id": {
			"type": "string"
		},
		"updated_at": {
			"type": "string",
			"format": "date-time"
		},
		"user_id": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"start_time",
		"survey_id",
		"user_id"
	]
}
