/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const SurveyResponseCommentUpdateSchema = {
	"type": "object",
	"properties": {
		"comment_id": {
			"type": "string"
		},
		"id": {
			"type": "string"
		},
		"survey_response_id": {
			"type": "string"
		}
	},
	"additionalProperties": false
}
