/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const SurveyScreenCreateSchema = {
	"type": "object",
	"properties": {
		"screen_number": {
			"type": "number"
		},
		"survey_id": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"screen_number",
		"survey_id"
	]
}
