/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const SurveyResponseCommentCreateSchema = {
	"type": "object",
	"properties": {
		"comment_id": {
			"type": "string"
		},
		"survey_response_id": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"comment_id",
		"survey_response_id"
	]
}
