/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const SurveyScreenComponentSchema = {
	"type": "object",
	"properties": {
		"answers_enabling_follow_up": {
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"component_number": {
			"type": "number"
		},
		"config": {
			"type": "string"
		},
		"detail_label": {
			"type": "string"
		},
		"id": {
			"type": "string"
		},
		"is_follow_up": {
			"type": "boolean"
		},
		"question_id": {
			"type": "string"
		},
		"question_label": {
			"type": "string"
		},
		"screen_id": {
			"type": "string"
		},
		"updated_at_sync_tick": {
			"type": "string"
		},
		"validation_criteria": {
			"type": "string"
		},
		"visibility_criteria": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"component_number",
		"id",
		"question_id",
		"screen_id",
		"updated_at_sync_tick"
	]
}
