/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const SurveySchema = {
	"type": "object",
	"properties": {
		"can_repeat": {
			"type": "boolean"
		},
		"code": {
			"type": "string"
		},
		"country_ids": {
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"data_group_id": {
			"type": "string"
		},
		"id": {
			"type": "string"
		},
		"integration_metadata": {
			"type": "object",
			"properties": {}
		},
		"name": {
			"type": "string"
		},
		"period_granularity": {
			"enum": [
				"daily",
				"monthly",
				"quarterly",
				"weekly",
				"yearly"
			],
			"type": "string"
		},
		"permission_group_id": {
			"type": "string"
		},
		"project_id": {
			"type": "string"
		},
		"requires_approval": {
			"type": "boolean"
		},
		"survey_group_id": {
			"type": "string"
		},
		"updated_at_sync_tick": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"code",
		"id",
		"name",
		"project_id",
		"updated_at_sync_tick"
	]
}
