/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const SurveyScreenSchema = {
	"type": "object",
	"properties": {
		"id": {
			"type": "string"
		},
		"screen_number": {
			"type": "number"
		},
		"survey_id": {
			"type": "string"
		},
		"updated_at_sync_tick": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"id",
		"screen_number",
		"survey_id",
		"updated_at_sync_tick"
	]
}
