/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const SurveyScreenUpdateSchema = {
	"type": "object",
	"properties": {
		"id": {
			"type": "string"
		},
		"screen_number": {
			"type": "number"
		},
		"survey_id": {
			"type": "string"
		}
	},
	"additionalProperties": false
}
