/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const SurveyResponseDraftSchema = {
	"type": "object",
	"properties": {
		"country_code": {
			"type": "string"
		},
		"entity_id": {
			"type": "string"
		},
		"form_data": {
			"type": "object",
			"properties": {}
		},
		"id": {
			"type": "string"
		},
		"is_deleted": {
			"type": "boolean"
		},
		"screen_number": {
			"type": "number"
		},
		"start_time": {
			"type": "string",
			"format": "date-time"
		},
		"survey_id": {
			"type": "string"
		},
		"updated_at": {
			"type": "string",
			"format": "date-time"
		},
		"updated_at_sync_tick": {
			"type": "string"
		},
		"user_id": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"form_data",
		"id",
		"is_deleted",
		"screen_number",
		"start_time",
		"survey_id",
		"updated_at",
		"updated_at_sync_tick",
		"user_id"
	]
}
