/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const SyncSessionInfoSchema = {
	"type": "object",
	"properties": {
		"beganPersistAt": {
			"anyOf": [
				{
					"type": "string",
					"format": "date-time"
				},
				{
					"type": "array",
					"items": {
						"type": "string"
					}
				}
			]
		},
		"deviceId": {
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"projectIds": {
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"totalToPull": {
			"type": "number"
		},
		"totalPushed": {
			"type": "number"
		}
	},
	"additionalProperties": false,
	"required": [
		"deviceId"
	]
}
