/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const SyncGroupLogCreateSchema = {
	"type": "object",
	"properties": {
		"log_message": {
			"type": "string"
		},
		"service_type": {
			"enum": [
				"data-lake",
				"dhis",
				"indicator",
				"kobo",
				"superset",
				"tupaia",
				"weather"
			],
			"type": "string"
		},
		"sync_group_code": {
			"type": "string"
		},
		"timestamp": {
			"type": "string",
			"format": "date-time"
		}
	},
	"additionalProperties": false,
	"required": [
		"log_message",
		"service_type",
		"sync_group_code"
	]
}
