/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const SyncGroupSyncStatusSchema = {
	"enum": [
		"ERROR",
		"IDLE",
		"SYNCING"
	],
	"type": "string"
}
