/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const SyncSessionUpdateSchema = {
	"type": "object",
	"properties": {
		"completed_at": {
			"type": "string",
			"format": "date-time"
		},
		"errors": {
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"id": {
			"type": "string"
		},
		"info": {
			"type": "object",
			"properties": {
				"beganPersistAt": {
					"anyOf": [
						{
							"type": "string",
							"format": "date-time"
						},
						{
							"type": "array",
							"items": {
								"type": "string"
							}
						}
					]
				},
				"deviceId": {
					"type": "array",
					"items": {
						"type": "string"
					}
				},
				"projectIds": {
					"type": "array",
					"items": {
						"type": "string"
					}
				},
				"totalToPull": {
					"type": "number"
				},
				"totalPushed": {
					"type": "number"
				}
			},
			"additionalProperties": false,
			"required": [
				"deviceId"
			]
		},
		"last_connection_time": {
			"type": "string",
			"format": "date-time"
		},
		"persist_completed_at": {
			"type": "string",
			"format": "date-time"
		},
		"pull_since": {
			"type": "string"
		},
		"pull_until": {
			"type": "string"
		},
		"snapshot_completed_at": {
			"type": "string",
			"format": "date-time"
		},
		"snapshot_started_at": {
			"type": "string",
			"format": "date-time"
		},
		"start_time": {
			"type": "string",
			"format": "date-time"
		},
		"started_at_tick": {
			"type": "string"
		}
	},
	"additionalProperties": false
}
