/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const SyncQueuedDeviceUpdateSchema = {
	"type": "object",
	"properties": {
		"id": {
			"type": "string"
		},
		"last_seen_time": {
			"type": "string",
			"format": "date-time"
		},
		"last_synced_tick": {
			"type": "string"
		},
		"urgent": {
			"type": "boolean"
		}
	},
	"additionalProperties": false
}
