/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const SystemCommentSubTypeSchema = {
	"enum": [
		"complete",
		"create",
		"overdue",
		"update"
	],
	"type": "string"
}
