/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const TaskQuestionConfigSchema = {
	"type": "object",
	"properties": {
		"shouldCreateTask": {
			"description": "Determines if a task should be created.",
			"type": "object",
			"properties": {
				"questionId": {
					"type": "string"
				}
			},
			"additionalProperties": false,
			"required": [
				"questionId"
			]
		},
		"entityId": {
			"description": "Determines the entity that the task will be created for.",
			"type": "object",
			"properties": {
				"questionId": {
					"type": "string"
				}
			},
			"additionalProperties": false,
			"required": [
				"questionId"
			]
		},
		"surveyCode": {
			"description": "Determines the survey that the task will be created for.",
			"type": "string"
		},
		"dueDate": {
			"description": "Determines the due date of the task.",
			"type": "object",
			"properties": {
				"questionId": {
					"type": "string"
				}
			},
			"additionalProperties": false,
			"required": [
				"questionId"
			]
		},
		"assignee": {
			"description": "Determines the assignee of the task.",
			"type": "object",
			"properties": {
				"questionId": {
					"type": "string"
				}
			},
			"additionalProperties": false,
			"required": [
				"questionId"
			]
		}
	},
	"additionalProperties": false,
	"required": [
		"assignee",
		"dueDate",
		"entityId",
		"shouldCreateTask",
		"surveyCode"
	]
}
