/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const TaskCreateCommentTemplateVariablesSchema = {
	"type": "object",
	"properties": {
		"type": {
			"type": "string",
			"enum": [
				"create"
			]
		}
	},
	"additionalProperties": false,
	"required": [
		"type"
	]
}
