/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const TaskUpdateCommentTemplateVariablesSchema = {
	"type": "object",
	"properties": {
		"type": {
			"type": "string",
			"enum": [
				"update"
			]
		},
		"originalValue": {
			"type": [
				"string",
				"number"
			]
		},
		"newValue": {
			"type": [
				"string",
				"number"
			]
		},
		"field": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"type"
	]
}
