/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const TaskStatusSchema = {
	"enum": [
		"cancelled",
		"completed",
		"to_do"
	],
	"type": "string"
}
