/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const TaskUpdateSchema = {
	"type": "object",
	"properties": {
		"assignee_id": {
			"type": "string"
		},
		"created_at": {
			"type": "string",
			"format": "date-time"
		},
		"due_date": {
			"type": "number"
		},
		"entity_id": {
			"type": "string"
		},
		"id": {
			"type": "string"
		},
		"initial_request_id": {
			"type": "string"
		},
		"overdue_email_sent": {
			"type": "string",
			"format": "date-time"
		},
		"parent_task_id": {
			"type": "string"
		},
		"repeat_schedule": {
			"additionalProperties": false,
			"type": "object",
			"properties": {
				"freq": {
					"type": "number"
				},
				"interval": {
					"type": "number"
				},
				"bymonthday": {
					"anyOf": [
						{
							"type": "array",
							"items": {
								"type": "number"
							}
						},
						{
							"type": "number"
						}
					]
				},
				"bysetpos": {
					"anyOf": [
						{
							"type": "array",
							"items": {
								"type": "number"
							}
						},
						{
							"type": "number"
						}
					]
				},
				"dtstart": {
					"type": "string",
					"format": "date-time"
				}
			}
		},
		"status": {
			"enum": [
				"cancelled",
				"completed",
				"to_do"
			],
			"type": "string"
		},
		"survey_id": {
			"type": "string"
		},
		"survey_response_id": {
			"type": "string"
		}
	},
	"additionalProperties": false
}
