/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const TaskCompletedCommentTemplateVariablesSchema = {
	"type": "object",
	"properties": {
		"type": {
			"type": "string",
			"enum": [
				"complete"
			]
		},
		"taskId": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"type"
	]
}
