/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const TaskCommentSchema = {
	"type": "object",
	"properties": {
		"created_at": {
			"type": "string",
			"format": "date-time"
		},
		"id": {
			"type": "string"
		},
		"message": {
			"type": "string"
		},
		"task_id": {
			"type": "string"
		},
		"template_variables": {
			"anyOf": [
				{
					"type": "object",
					"properties": {
						"type": {
							"type": "string",
							"enum": [
								"update"
							]
						},
						"originalValue": {
							"type": [
								"string",
								"number"
							]
						},
						"newValue": {
							"type": [
								"string",
								"number"
							]
						},
						"field": {
							"type": "string"
						}
					},
					"additionalProperties": false,
					"required": [
						"type"
					]
				},
				{
					"type": "object",
					"properties": {
						"type": {
							"type": "string",
							"enum": [
								"create"
							]
						}
					},
					"additionalProperties": false,
					"required": [
						"type"
					]
				},
				{
					"type": "object",
					"properties": {
						"type": {
							"type": "string",
							"enum": [
								"complete"
							]
						},
						"taskId": {
							"type": "string"
						}
					},
					"additionalProperties": false,
					"required": [
						"type"
					]
				}
			]
		},
		"type": {
			"enum": [
				"system",
				"user"
			],
			"type": "string"
		},
		"updated_at_sync_tick": {
			"type": "string"
		},
		"user_id": {
			"type": "string"
		},
		"user_name": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"created_at",
		"id",
		"task_id",
		"template_variables",
		"type",
		"updated_at_sync_tick",
		"user_name"
	]
}
