/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const UnsubscribeDashboardRequestSchema = {
	"type": "object",
	"properties": {
		"email": {
			"type": "string"
		},
		"unsubscribeTime": {
			"type": "string",
			"format": "date-time"
		}
	},
	"additionalProperties": false,
	"required": [
		"email",
		"unsubscribeTime"
	]
}
