/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const UserSessionUpdateSchema = {
	"type": "object",
	"properties": {
		"access_token_expiry": {
			"type": "string"
		},
		"accessPolicy": {
			"type": "object",
			"properties": {}
		},
		"accessToken": {
			"type": "string"
		},
		"id": {
			"type": "string"
		},
		"refreshToken": {
			"type": "string"
		},
		"userName": {
			"type": "string"
		}
	},
	"additionalProperties": false
}
