/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const UserEntityPermissionSchema = {
	"type": "object",
	"properties": {
		"entity_id": {
			"type": "string"
		},
		"id": {
			"type": "string"
		},
		"permission_group_id": {
			"type": "string"
		},
		"updated_at_sync_tick": {
			"type": "string"
		},
		"user_id": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"entity_id",
		"id",
		"permission_group_id",
		"updated_at_sync_tick",
		"user_id"
	]
}
