/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const UserEntityPermissionUpdateSchema = {
	"type": "object",
	"properties": {
		"entity_id": {
			"type": "string"
		},
		"id": {
			"type": "string"
		},
		"permission_group_id": {
			"type": "string"
		},
		"user_id": {
			"type": "string"
		}
	},
	"additionalProperties": false
}
