/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const UserFavouriteDashboardItemUpdateSchema = {
	"type": "object",
	"properties": {
		"dashboard_item_id": {
			"type": "string"
		},
		"id": {
			"type": "string"
		},
		"user_id": {
			"type": "string"
		}
	},
	"additionalProperties": false
}
