/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const UserCountryAccessAttemptCreateSchema = {
	"type": "object",
	"properties": {
		"country_code": {
			"type": "string"
		},
		"user_id": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"country_code",
		"user_id"
	]
}
