/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const UserAccountCreateSchema = {
	"type": "object",
	"properties": {
		"creation_date": {
			"type": "string",
			"format": "date-time"
		},
		"email": {
			"type": "string"
		},
		"employer": {
			"type": "string"
		},
		"first_name": {
			"type": "string"
		},
		"gender": {
			"type": "string"
		},
		"last_name": {
			"type": "string"
		},
		"legacy_password_salt": {
			"type": "string"
		},
		"mobile_number": {
			"type": "string"
		},
		"password_hash": {
			"type": "string"
		},
		"position": {
			"type": "string"
		},
		"preferences": {
			"type": "object",
			"properties": {
				"country_id": {
					"type": "string"
				},
				"project_id": {
					"type": "string"
				},
				"recent_entities": {
					"type": "object",
					"additionalProperties": false
				},
				"delete_account_requested": {
					"type": "boolean"
				},
				"hide_welcome_screen": {
					"type": "boolean"
				}
			},
			"additionalProperties": false
		},
		"primary_platform": {
			"enum": [
				"datatrak",
				"lesmis",
				"tupaia"
			],
			"type": "string"
		},
		"profile_image": {
			"type": "string"
		},
		"verified_email": {
			"enum": [
				"new_user",
				"unverified",
				"verified"
			],
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"email",
		"password_hash"
	]
}
