/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const UserAccountPreferencesSchema = {
	"type": "object",
	"properties": {
		"country_id": {
			"type": "string"
		},
		"project_id": {
			"type": "string"
		},
		"recent_entities": {
			"type": "object",
			"additionalProperties": false
		},
		"delete_account_requested": {
			"type": "boolean"
		},
		"hide_welcome_screen": {
			"type": "boolean"
		}
	},
	"additionalProperties": false
}
