/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const UserFavouriteDashboardItemSchema = {
	"type": "object",
	"properties": {
		"dashboard_item_id": {
			"type": "string"
		},
		"id": {
			"type": "string"
		},
		"user_id": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"dashboard_item_id",
		"id",
		"user_id"
	]
}
