/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const UserEntityPermissionCreateSchema = {
	"type": "object",
	"properties": {
		"entity_id": {
			"type": "string"
		},
		"permission_group_id": {
			"type": "string"
		},
		"user_id": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"entity_id",
		"permission_group_id",
		"user_id"
	]
}
