/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const UserQuestionConfigSchema = {
	"type": "object",
	"properties": {
		"permissionGroup": {
			"description": "Filters the users by permission group.",
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"permissionGroup"
	]
}
