/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const ValidationCriteriaSchema = {
	"type": "object",
	"properties": {
		"mandatory": {
			"type": "boolean"
		},
		"min": {
			"type": "number"
		},
		"max": {
			"type": "number"
		}
	},
	"additionalProperties": false
}
