/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const ValueKeySchema = {
	"description": "A key that can be used to reference a value in a measureConfig, or to reference all values",
	"type": "string"
}
