/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const ViewReportSchema = {
	"additionalProperties": false,
	"type": "object",
	"properties": {
		"startDate": {
			"type": "string"
		},
		"endDate": {
			"type": "string"
		},
		"period": {
			"type": "object",
			"properties": {
				"earliestAvailable": {
					"type": "string"
				},
				"latestAvailable": {
					"type": "string"
				},
				"requested": {
					"type": "string"
				}
			},
			"additionalProperties": false
		},
		"type": {
			"enum": [
				"default",
				"rawDataExport"
			],
			"type": "string"
		},
		"data": {
			"type": "array",
			"items": {
				"anyOf": [
					{
						"type": "object",
						"properties": {
							"uniqueFileName": {
								"type": "string"
							},
							"label": {
								"type": "string"
							}
						},
						"additionalProperties": false,
						"required": [
							"label",
							"uniqueFileName"
						]
					},
					{
						"additionalProperties": false,
						"type": "object",
						"properties": {
							"value": {},
							"total": {
								"type": "number"
							},
							"viewType": {
								"enum": [
									"dataDownload",
									"filesDownload",
									"multiPhotograph",
									"multiSingleValue",
									"multiValue",
									"multiValueRow",
									"qrCodeVisual",
									"singleDate",
									"singleDownloadLink",
									"singleValue"
								],
								"type": "string"
							},
							"label": {
								"type": "string"
							}
						}
					}
				]
			}
		},
		"downloadUrl": {
			"type": "string"
		}
	},
	"required": [
		"endDate",
		"startDate"
	]
}
