/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const ViewDataItemSchema = {
	"anyOf": [
		{
			"type": "object",
			"properties": {
				"uniqueFileName": {
					"type": "string"
				},
				"label": {
					"type": "string"
				}
			},
			"additionalProperties": false,
			"required": [
				"label",
				"uniqueFileName"
			]
		},
		{
			"additionalProperties": false,
			"type": "object",
			"properties": {
				"value": {},
				"total": {
					"type": "number"
				},
				"viewType": {
					"enum": [
						"dataDownload",
						"filesDownload",
						"multiPhotograph",
						"multiSingleValue",
						"multiValue",
						"multiValueRow",
						"qrCodeVisual",
						"singleDate",
						"singleDownloadLink",
						"singleValue"
					],
					"type": "string"
				},
				"label": {
					"type": "string"
				}
			}
		}
	]
}
