/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const ViewPresentationOptionsSchema = {
	"anyOf": [
		{
			"additionalProperties": false,
			"type": "object",
			"properties": {
				"isTitleVisible": {
					"type": "boolean"
				},
				"valueFormat": {
					"description": "This can be anything from the [numeraljs library]{@link http://numeraljs.com/#format}",
					"type": "string"
				}
			}
		},
		{
			"additionalProperties": false,
			"type": "object",
			"properties": {
				"color": {
					"description": "A CSS color string e.g. green or #abc123",
					"type": "string"
				},
				"header": {
					"type": "string"
				},
				"dataPairNames": {
					"type": "array",
					"items": {
						"type": "string"
					}
				},
				"rowHeader": {
					"additionalProperties": false,
					"type": "object",
					"properties": {
						"color": {
							"description": "A CSS color string e.g. green or #abc123",
							"type": "string"
						},
						"name": {
							"type": "string"
						}
					},
					"required": [
						"color"
					]
				},
				"leftColumn": {
					"additionalProperties": false,
					"type": "object",
					"properties": {
						"color": {
							"description": "A CSS color string e.g. green or #abc123",
							"type": "string"
						},
						"header": {
							"type": "string"
						}
					},
					"required": [
						"color",
						"header"
					]
				},
				"rightColumn": {
					"additionalProperties": false,
					"type": "object",
					"properties": {
						"color": {
							"description": "A CSS color string e.g. green or #abc123",
							"type": "string"
						},
						"header": {
							"type": "string"
						}
					},
					"required": [
						"color",
						"header"
					]
				},
				"middleColumn": {
					"additionalProperties": false,
					"type": "object",
					"properties": {
						"color": {
							"description": "A CSS color string e.g. green or #abc123",
							"type": "string"
						},
						"header": {
							"type": "string"
						}
					},
					"required": [
						"color",
						"header"
					]
				}
			},
			"required": [
				"color",
				"header"
			]
		}
	]
}
