/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const VisibilityCriteriaSchema = {
	"additionalProperties": false,
	"type": "object",
	"properties": {
		"_conjunction": {
			"type": "string"
		}
	}
}
