/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const VizPeriodGranularitySchema = {
	"enum": [
		"day",
		"month",
		"one_day_at_a_time",
		"one_month_at_a_time",
		"one_quarter_at_a_time",
		"one_week_at_a_time",
		"one_year_at_a_time",
		"quarter",
		"week",
		"year"
	],
	"type": "string"
}
