/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const WeekDisplayFormatSchema = {
	"enum": [
		"ISO_WEEK_NUMBER",
		"WEEK_COMMENCING",
		"WEEK_COMMENCING_ABBR",
		"WEEK_ENDING",
		"WEEK_ENDING_ABBR"
	],
	"type": "string"
}
