/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const YAxisDomainEntrySchema = {
	"type": "object",
	"properties": {
		"type": {
			"enum": [
				"clamp",
				"number",
				"scale",
				"string"
			],
			"type": "string"
		},
		"value": {
			"type": [
				"string",
				"number"
			]
		},
		"min": {
			"type": "number"
		},
		"max": {
			"type": "number"
		}
	},
	"additionalProperties": false,
	"required": [
		"type"
	]
}
