/*
 * This file was generated by a tool.
 * Rerun generate:schemas to regenerate this file.
 */
export const YAxisDomainSchema = {
	"type": "object",
	"properties": {
		"max": {
			"description": "Domain configuration for the maximum y axis value.\neg.\n// Cannot be higher than 100\n{\n  type: number\n  value: 100\n}\n\n// Clamp between 50, the maximum data value, and 100\n{\n  type: clamp\n  min: 50\n  max: 100\n}\n\n// Scale the y axis to always be 10% higher than the maximum data value\n{\n  type: scale\n  value: 1.1\n}\n\n// 20 greater than the maximum data value\n{\n  type: string\n  value: datamax + 20\n}\n\nFor more options see: https://recharts.org/en-US/api/YAxis#domain",
			"type": "object",
			"properties": {
				"type": {
					"enum": [
						"clamp",
						"number",
						"scale",
						"string"
					],
					"type": "string"
				},
				"value": {
					"type": [
						"string",
						"number"
					]
				},
				"min": {
					"type": "number"
				},
				"max": {
					"type": "number"
				}
			},
			"additionalProperties": false,
			"required": [
				"type"
			]
		},
		"min": {
			"description": "Domain configuration for the minimum y axis value.\neg.\n// Cannot be lower than 0\n{\n  type: number\n  value: 0\n}\n\n// Clamp between 0, the minimum data value, and 10\n{\n  type: clamp\n  min: 0\n  max: 10\n}\n\n// Scale the y axis to always be 10% lower than the minimum data value\n{\n  type: scale\n  value: 0.9\n}\n\n// 20 less than the minimum data value\n{\n  type: string\n  value: datamin - 20\n}\n\nFor more options see: https://recharts.org/en-US/api/YAxis#domain",
			"type": "object",
			"properties": {
				"type": {
					"enum": [
						"clamp",
						"number",
						"scale",
						"string"
					],
					"type": "string"
				},
				"value": {
					"type": [
						"string",
						"number"
					]
				},
				"min": {
					"type": "number"
				},
				"max": {
					"type": "number"
				}
			},
			"additionalProperties": false,
			"required": [
				"type"
			]
		}
	},
	"additionalProperties": false,
	"required": [
		"max",
		"min"
	]
}
