import { AnalyticsRefresher } from '../../server/changeHandlers';

const TABLES_TO_CLEAR = /** @type {const} */ ([
  // 'analytics',
  'access_request',
  'admin_panel_session',
  'ancestor_descendant_relation',
  'answer',
  'api_client',
  'api_request_log',
  'clinic',
  'comment',
  'country',
  'dashboard_item',
  'dashboard_mailing_list_entry',
  'dashboard_mailing_list',
  'dashboard_relation',
  'dashboard',
  'data_element_data_group',
  'data_element_data_service',
  'data_element',
  'data_group',
  'data_service_entity',
  'data_service_sync_group',
  'data_table',
  'datatrak_session',
  'dhis_instance',
  'dhis_sync_log',
  'dhis_sync_queue',
  'entity_hierarchy',
  'entity_parent_child_relation',
  'entity_relation',
  'entity',
  'error_log',
  'external_database_connection',
  'feed_item',
  'geographical_area',
  'indicator',
  'landing_page',
  'legacy_report',
  'lesmis_session',
  'local_system_fact',
  // 'log$_answer',
  // 'log$_data_element',
  // 'log$_entity',
  // 'log$_question',
  // 'log$_survey_response',
  // 'log$_survey',
  'login_attempts',
  'map_overlay_group_relation',
  'map_overlay_group',
  'map_overlay',
  'meditrak_device',
  'meditrak_sync_queue',
  // 'migrations',
  'ms1_sync_log',
  'ms1_sync_queue',
  'one_time_login',
  'option_set',
  'option',
  'permission_group',
  'project',
  'psss_session',
  'question',
  'refresh_token',
  'report',
  'setting',
  // 'spatial_ref_sys',
  'superset_instance',
  'survey_group',
  'survey_response_comment',
  'survey_response',
  'survey_screen_component',
  'survey_screen',
  'survey',
  'sync_device_tick',
  'sync_group_log',
  'sync_lookup',
  'sync_queued_device',
  'sync_session',
  'task_comment',
  'task',
  'tupaia_web_session',
  'user_account',
  'user_country_access_attempt',
  'user_entity_permission',
  'user_favourite_dashboard_item',
  'userSession',
]);

export async function clearTestData(db) {
  // Safety check
  const [{ current_database }] = await db.executeSql('SELECT current_database();');
  if (current_database !== 'tupaia_test') {
    throw new Error(
      `Safety check failed: clearTestData can only be run against a database named tupaia_test, found ${current_database}.`,
    );
  }

  const sql = TABLES_TO_CLEAR.map(() => 'TRUNCATE TABLE ?? CASCADE;').join('\n');
  await db.wrapInTransaction(async db => {
    await db.executeSql(sql, TABLES_TO_CLEAR);
  });

  await AnalyticsRefresher.refreshAnalytics(db);
}
