export const LOGS_DATA_FETCH_BEGIN = 'LOGS_DATA_FETCH_BEGIN';
export const LOGS_DATA_FETCH_SUCCESS = 'LOGS_DATA_FETCH_SUCCESS';
export const LOGS_DISMISS = 'LOGS_DISMISS';
export const LOGS_ERROR = 'LOGS_ERROR';
export const LOGS_OPEN = 'LOGS_OPEN';
