/**
 * Tupaia MediTrak
 * Copyright (c) 2017 Beyond Essential Systems Pty Ltd
 */

export const TYPES = {
  REFRESH_TOKEN: 'refresh_token',
  MEDITRAK_SYNC_QUEUE: 'meditrak_sync_queue',
  MS1_SYNC_QUEUE: 'ms1_sync_queue',
  MS1_SYNC_LOG: 'ms1_sync_log',
  ENTITY: 'entity',
  FACILITY: 'clinic',
  ENTITY_RELATION: 'entity_relation',
  ENTITY_RELATION_TYPE: 'entity_relation_type',
  API_CLIENT: 'api_client',
  USER_ACCOUNT: 'user_account',
  USER_COUNTRY_PERMISSION: 'user_country_permission',
  PERMISSION_GROUP: 'permission_group',
  COUNTRY: 'country',
  GEOGRAPHICAL_AREA: 'geographical_area',
  QUESTION: 'question',
  SURVEY: 'survey',
  SURVEY_GROUP: 'survey_group',
  SURVEY_SCREEN: 'survey_screen',
  SURVEY_SCREEN_COMPONENT: 'survey_screen_component',
  SURVEY_RESPONSE: 'survey_response',
  ANSWER: 'answer',
  DHIS_SYNC_LOG: 'dhis_sync_log',
  DHIS_SYNC_QUEUE: 'dhis_sync_queue',
  API_REQUEST_LOG: 'api_request_log',
  SETTING: 'setting',
  FEED_ITEM: 'feed_item',
  USER_GEOGRAPHICAL_AREA_PERMISSION: 'user_geographical_area_permission',
  USER_REWARD: 'user_reward',
  INSTALL_ID: 'install_id',
  USER_FACILITY_PERMISSION: 'user_clinic_permission',
  ONE_TIME_LOGIN: 'one_time_login',
  OPTION: 'option',
  OPTION_SET: 'option_set',
  DISASTER: 'disaster',
  DISASTER_EVENT: 'disasterEvent',
};
