/**
 * Tupaia MediTrak
 * Copyright (c) 2017 Beyond Essential Systems Pty Ltd
 */

export const ANSWER_CHANGE = 'ANSWER_CHANGE';
export const EXTRA_PROPS_CHANGE = 'EXTRA_PROPS_CHANGE';
export const SURVEY_SELECT = 'SURVEY_SELECT';
export const SURVEY_SCREEN_SELECT = 'SURVEY_SCREEN_SELECT';
export const SURVEY_SUBMIT = 'SURVEY_SUBMIT';
export const SURVEY_SUBMIT_SUCCESS = 'SURVEY_SUBMIT_SUCCESS';
export const UPDATE_SURVEYS = 'UPDATE_SURVEYS';
export const WIPE_CURRENT_SURVEY = 'WIPE_CURRENT_SURVEY';
export const ASSESSMENT_RESET = 'ASSESSMENT_RESET';
export const VALIDATION_ERROR_CHANGE = 'VALIDATION_ERROR_CHANGE';
export const SURVEY_SCREEN_ERROR_MESSAGE_CHANGE = 'SURVEY_SCREEN_ERROR_MESSAGE_CHANGE';
export const SCROLL_CONTROL_ATTACH = 'SCROLL_CONTROL_ATTACH';
export const SCROLL_CONTROL_RELEASE = 'SCROLL_CONTROL_RELEASE';
