export const RESUBMIT_SURVEY_RESPONSE_OPEN = 'RESUBMIT_SURVEY_RESPONSE_OPEN';
export const RESUBMIT_SURVEY_DISMISS = 'RESUBMIT_SURVEY_DISMISS';
export const EDIT_SURVEY_RESPONSE_START = 'RESUMIT_SURVEY_START';
export const EDIT_SURVEY_RESPONSE_END = 'EDIT_SURVEY_RESPONSE_END';
export const EDIT_SURVEY_RESPONSE_ERROR = 'EDIT_SURVEY_RESPONSE_ERROR';

export const ARCHIVE_SURVEY_RESPONSE_OPEN = 'ARCHIVE_SURVEY_RESPONSE_OPEN';
export const ARCHIVE_SURVEY_RESPONSE_DISMISS = 'ARCHIVE_SURVEY_RESPONSE_DISMISS';

export const DATA_CHANGE_ACTIONS = {
  start: EDIT_SURVEY_RESPONSE_START,
  finish: EDIT_SURVEY_RESPONSE_END,
  error: EDIT_SURVEY_RESPONSE_ERROR,
};

export const MODAL_STATUS = {
  INITIAL: 'initial',
  LOADING: 'loading',
  ERROR: 'error',
  SUCCESS: 'success',
};
