export enum ACTION_TYPES {
  SET_FORM_DATA = 'SET_FORM_DATA',
  TOGGLE_SIDE_MENU = 'TOGGLE_SIDE_MENU',
  RESET_FORM_DATA = 'RESET_FORM_DATA',
  SET_SURVEY_START_TIME = 'SET_SURVEY_START_TIME',
  OPEN_CANCEL_CONFIRMATION = 'OPEN_CANCEL_CONFIRMATION',
  CLOSE_CANCEL_CONFIRMATION = 'CLOSE_CANCEL_CONFIRMATION',
}

export type SurveyFormAction = {
  type: ACTION_TYPES;
  payload?: Record<string, any> | string | null;
};
