/**
 * Tupaia MediTrak
 * Copyright (c) 2017 Beyond Essential Systems Pty Ltd
 */

export const ENTITY_SEARCH_TERM_CHANGE = 'ENTITY_SEARCH_TERM_CHANGE';
export const ENTITY_RECEIVE_ENTITIES = 'ENTITY_RECEIVE_ENTITIES';
export const ENTITY_RECEIVE_PRIMARY_ENTITIES = 'ENTITY_RECEIVE_PRIMARY_ENTITIES';
