export const SOCIAL_FEED_REQUEST = 'SOCIAL_FEED_REQUEST';
export const SOCIAL_FEED_SUCCESS = 'SOCIAL_FEED_SUCCESS';
export const SOCIAL_FEED_FAILURE = 'SOCIAL_FEED_FAILURE';
export const SOCIAL_FEED_RESET = 'SOCIAL_FEED_RESET';
