/**
 * Tupaia MediTrak
 * Copyright (c) 2017 Beyond Essential Systems Pty Ltd
 */

export const TYPES = {
  ANALYTICS: 'analytics',
  ANCESTOR_DESCENDANT_RELATION: 'ancestor_descendant_relation',
  ANSWER: 'answer',
  ACCESS_REQUEST: 'access_request',
  API_CLIENT: 'api_client',
  API_REQUEST_LOG: 'api_request_log',
  COMMENT: 'comment',
  COUNTRY: 'country',
  DASHBOARD: 'dashboard',
  DASHBOARD_ITEM: 'dashboard_item',
  DASHBOARD_RELATION: 'dashboard_relation',
  DATA_ELEMENT_DATA_GROUP: 'data_element_data_group',
  DATA_ELEMENT_DATA_SERVICE: 'data_element_data_service',
  DATA_ELEMENT: 'data_element',
  DATA_GROUP: 'data_group',
  DATA_SERVICE_ENTITY: 'data_service_entity',
  DATA_SERVICE_SYNC_GROUP: 'data_service_sync_group',
  DATA_TABLE: 'data_table',
  DHIS_INSTANCE: 'dhis_instance',
  DHIS_SYNC_LOG: 'dhis_sync_log',
  DHIS_SYNC_QUEUE: 'dhis_sync_queue',
  DISASTER: 'disaster',
  DISASTER_EVENT: 'disasterEvent',
  ENTITY_HIERARCHY: 'entity_hierarchy',
  ENTITY_RELATION: 'entity_relation',
  ENTITY: 'entity',
  ERROR_LOG: 'error_log',
  EXTERNAL_DATABASE_CONNECTION: 'external_database_connection',
  FACILITY: 'clinic',
  FEED_ITEM: 'feed_item',
  GEOGRAPHICAL_AREA: 'geographical_area',
  INDICATOR: 'indicator',
  LEGACY_REPORT: 'legacy_report',
  MAP_OVERLAY: 'map_overlay',
  MAP_OVERLAY_GROUP: 'map_overlay_group',
  MAP_OVERLAY_GROUP_RELATION: 'map_overlay_group_relation',
  MEDITRAK_DEVICE: 'meditrak_device',
  MEDITRAK_SYNC_QUEUE: 'meditrak_sync_queue',
  MS1_SYNC_LOG: 'ms1_sync_log',
  MS1_SYNC_QUEUE: 'ms1_sync_queue',
  ONE_TIME_LOGIN: 'one_time_login',
  OPTION_SET: 'option_set',
  OPTION: 'option',
  PERMISSION_GROUP: 'permission_group',
  PROJECT: 'project',
  QUESTION: 'question',
  REFRESH_TOKEN: 'refresh_token',
  REPORT: 'report',
  SUPERSET_INSTANCE: 'superset_instance',
  SETTING: 'setting',
  SURVEY_GROUP: 'survey_group',
  SURVEY_RESPONSE: 'survey_response',
  SURVEY_RESPONSE_COMMENT: 'survey_response_comment',
  SURVEY_SCREEN_COMPONENT: 'survey_screen_component',
  SURVEY_SCREEN: 'survey_screen',
  SURVEY: 'survey',
  SYNC_GROUP_LOG: 'sync_group_log',
  USER_ACCOUNT: 'user_account',
  USER_ENTITY_PERMISSION: 'user_entity_permission',
  USER_FAVOURITE_DASHBOARD_ITEM: 'user_favourite_dashboard_item',
  USER_SESSION: 'userSession',
};
