/**
 * Tupaia MediTrak
 * Copyright (c) 2017 Beyond Essential Systems Pty Ltd
 */

export const TYPES = {
  ANSWER: 'answer',
  API_CLIENT: 'api_client',
  API_REQUEST_LOG: 'api_request_log',
  COUNTRY: 'country',
  DASHBOARD_GROUP: 'dashboardGroup',
  DASHBOARD_REPORT: 'dashboardReport',
  DATA_ELEMENT_DATA_GROUP: 'data_element_data_group',
  DATA_SOURCE: 'data_source',
  DHIS_SYNC_LOG: 'dhis_sync_log',
  DHIS_SYNC_QUEUE: 'dhis_sync_queue',
  DISASTER: 'disaster',
  DISASTER_EVENT: 'disasterEvent',
  ENTITY_HIERARCHY: 'entity_hierarchy',
  ENTITY_RELATION_TYPE: 'entity_relation_type',
  ENTITY_RELATION: 'entity_relation',
  ENTITY: 'entity',
  ERROR_LOG: 'error_log',
  FACILITY: 'clinic',
  FEED_ITEM: 'feed_item',
  GEOGRAPHICAL_AREA: 'geographical_area',
  MAP_OVERLAY: 'mapOverlay',
  MEDITRAK_DEVICE: 'meditrak_device',
  MEDITRAK_SYNC_QUEUE: 'meditrak_sync_queue',
  MS1_SYNC_LOG: 'ms1_sync_log',
  MS1_SYNC_QUEUE: 'ms1_sync_queue',
  ONE_TIME_LOGIN: 'one_time_login',
  OPTION_SET: 'option_set',
  OPTION: 'option',
  PERMISSION_GROUP: 'permission_group',
  PROJECT: 'project',
  QUESTION: 'question',
  REFRESH_TOKEN: 'refresh_token',
  SETTING: 'setting',
  SURVEY_GROUP: 'survey_group',
  SURVEY_RESPONSE: 'survey_response',
  SURVEY_SCREEN_COMPONENT: 'survey_screen_component',
  SURVEY_SCREEN: 'survey_screen',
  SURVEY: 'survey',
  USER_ACCOUNT: 'user_account',
  USER_COUNTRY_PERMISSION: 'user_country_permission',
  USER_FACILITY_PERMISSION: 'user_clinic_permission',
  USER_GEOGRAPHICAL_AREA_PERMISSION: 'user_geographical_area_permission',
  USER_REWARD: 'user_reward',
  USER_SESSION: 'userSession',
};
