/**
 * Tupaia MediTrak
 * Copyright (c) 2017 Beyond Essential Systems Pty Ltd
 */

export const EMAIL_ADDRESS_CHANGE = 'EMAIL_ADDRESS_CHANGE';
export const PASSWORD_CHANGE = 'PASSWORD_CHANGE';
export const REMEMBER_ME_CHANGE = 'REMEMBER_ME_CHANGE';
export const LOGIN_MODAL_TOGGLE = 'LOGIN_MODAL_TOGGLE';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';

export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_REQUEST = 'PROFILE_REQUEST';
export const PROFILE_ERROR = 'PROFILE_ERROR';

export const PASSWORD_SUCCESS = 'PASSWORD_SUCCESS';
export const PASSWORD_REQUEST = 'PASSWORD_REQUEST';
export const PASSWORD_ERROR = 'PASSWORD_ERROR';
