/**
 * Tupaia MediTrak
 * Copyright (c) 2017 Beyond Essential Systems Pty Ltd
 */
export const COUNTRY_REQUEST_STATUSES = {
  COUNTRY_REQUEST_IDLE: 'COUNTRY_REQUEST_IDLE',
  COUNTRY_REQUESTING: 'COUNTRY_REQUESTING',
  COUNTRY_REQUEST_SUCCESS: 'COUNTRY_REQUEST_SUCCESS',
};
export const COUNTRY_ACCESS_REQUEST_START = 'COUNTRY_ACCESS_REQUEST_START';
export const COUNTRY_ACCESS_REQUEST_SUCCESS = 'COUNTRY_ACCESS_REQUEST_SUCCESS';
export const COUNTRY_ACCESS_REQUEST_FAIL = 'COUNTRY_ACCESS_REQUEST_FAIL';
export const FORM_RESET = 'FORM_RESET';
export const COUNTRY_ACCESS_FORM_FIELD_VALUES_SET = 'COUNTRY_ACCESS_FORM_FIELD_VALUES_SET';
export const INIT_COUNTRIES = 'INIT_COUNTRIES';
export const COUNTRY_SELECT = 'COUNTRY_SELECT';
export const COUNTRY_MENU_SHOW = 'COUNTRY_MENU_SHOW';
export const COUNTRY_MENU_HIDE = 'COUNTRY_MENU_HIDE';
export const RECEIVE_COUNTRIES = 'RECEIVE_COUNTRIES';
