export const LATEST_SERVER_SYNC_TIMESTAMP = 'LATEST_SERVER_SYNC_TIMESTAMP';
export const CURRENT_USER_EMAIL = 'LOGGED_IN_USER_EMAIL_ADDRESS';
export const PERMISSION_GROUPS_SYNCED = 'PERMISSION_GROUPS_SYNCED';
export const COUNTRIES_SYNCED = 'COUNTRIES_SYNCED';
