name: Hello World
on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Hello World
        run: echo "Hello World"
        shell: bash
