#!/bin/sh
# Copy the env files generated by the downloadEnv container into package dirs.
# Run by the frontend container prior to nginx startup
tupaia_env_dir=${TUPAIA_ENV_DIR:-/env/packages}
tupaia_package_dir=${TUPAIA_PACKAGE_DIR:-/home/ubuntu/tupaia/packages}

for p in "$tupaia_package_dir"/*; do
    package=$(basename "$p")
    if [ -f "$tupaia_env_dir/$package/.env" ]; then
        cp -v "$tupaia_env_dir/$package/.env" "$p/.env"
    fi
done
